rule test_pandas_left_minus_join:
    input:
        left = "table1.tsv",
        right = "table2.tsv"
    output:
        "left_minus_join.tsv"
    params:
        header = 0,
        index = ["chr", "pos", "ref"]
    log:
        "left_minus_join.log"
    wrapper:
        "master/bio/pandas/left_minus_join"
