rule test_deeptools_plotheatmap:
    input:
        archive = "archive.gz"
    output:
        plot = "heatmap.png"
    message:
        "Testing deeptools plotheatmap"
    threads:
        1
    resources:
        mem_mb = (
            lambda wildcards, attempt: min(attempt * 1024, 10240)
        ),
        time_min = (
            lambda wildcards, attempt: min(attempt * 20, 200)
        )
    log:
        "logs/test_deeptools_plotheatmap.log"
    wrapper:
        "master/bio/deeptools/plotHeatmap"
