name: tar
url: https://www.gnu.org/software/tar/
description: |
  GNU Tar provides the ability to create tar archives, as well as various other kinds
  of manipulation.
author:
  - Thibault Dayris
input:
  - data: Optional list of path(s) to data to (un)compress or concatenate
  - files_list: Optional path to a text file listing paths to files to (un)compress or concatenate
  - exclusion_list: Optional path to a text file listing file(s) to exclude from uncompression
output:
  - archive: Optional path to output archive
  - data: Optional path to output uncompressed file(s)
params:
  - extra: Optional parameters, besides `--file`, `--exclude-from`, `--files-from`
  - explicit_owner: Boolean. If `true`, explicitely set `--owner`
  - explicit_group: Boolean. If `true`, explicitely set `--group`
notes: |
  Archive format is automatically inferred if `snakemake.output.archive` is provided.
