rule vembrane_filter:
    input:
        vcf="in.vcf",
    output:
        vcf="filtered/out.vcf",
    log:
        "logs/vembrane.log",
    params:
        expression="POS > 4000",
        extra="",
    wrapper:
        "master/bio/vembrane/filter"
