rule filtlong:
    input:
        reads="{sample}.fastq",
    output:
        "{sample}.filtered.fastq",
    log:
        "logs/filtlong/test/{sample}.log",
    params:
        extra=" --mean_q_weight 5.0",
        target_bases=10,
    wrapper:
        "master/bio/filtlong"
