rule sort_bam:
    input:
        "mapped/{sample}.bam",
    output:
        "sorted/{sample}.bam",
    log:
        "logs/picard/sort_sam/{sample}.log",
    # optional specification of memory usage of the JVM that snakemake will respect with global
    # resource restrictions (https://snakemake.readthedocs.io/en/latest/snakefiles/rules.html#resources)
    # and which can be used to request RAM during cluster job submission as `{resources.mem_mb}`:
    # https://snakemake.readthedocs.io/en/latest/executing/cluster.html#job-properties
    resources:
        mem_mb=1024,
    params:
        sort_order="coordinate",
        extra="--VALIDATION_STRINGENCY LENIENT",  # optional: Extra arguments for picard.
    wrapper:
        "master/bio/picard/sortsam"
