name: grex
url: https://github.com/pemistahl/grex
description:
  A command-line tool used to generate regular expressions from user-provided test cases
author:
  - Thibault Dayris
input:
  - test_cases: Path to a file holding test cases to keep
output:
  - Path to regular expression
params:
  - extra: Optional parameters, besides `--file`
