include: "rules/000.common.smk"
include: "rules/001.bigr_copy.smk"
include: "rules/002.trimming.smk"
include: "rules/003.bowtie2.smk"
include: "rules/004.sambamba.smk"
include: "rules/005.samtools.smk"
include: "rules/006.bedtools_bam2bed.smk"
include: "rules/008.genomecov.smk"
include: "rules/010.macs2.smk"
include: "rules/011.deeptools.smk"
include: "rules/012.mapping_qc.smk"
include: "rules/013.multiqc.smk"
include: "rules/009.seacr.smk"


rule target:
    input:
        **targets()
