rule test_maftools_titv:
    input:
        rds = "maf.RDS"
    output:
        tsv = "results/titv.tsv",
        png = "results/titv.png",
        rds = "results/titv.RDS"
    wrapper:
        "master/bio/maftools/titv"
