rule test_analyze_cpat:
    input:
        switch_list = "switch_list.RDS",
        pfam = "pfam_results.txt"
    output:
        rds = "switch_list_with_pfam.RDS"
    wrapper:
        "master/bio/isoformSwitchAnalyzeR/analyzePFAM"
