---
name: gleaves_compatibility
description: Annotate a VCF file with required fields from GLeaves and additional information
authors:
  - Thibault Dayris
input:
  - vcf: The VCF to annotate
output:
  - vcf: The annotated VCF
notes: |
  ARCp = ALT depth on + strand

  ARCm = ALT depth on - strand

  RRCm = REF depth on + strand

  RRCp = ALT depth on - strand

  VAR = Genotype Quality
  
  * LSC Likely subclonal (VAF 0-10%)
  * PSC Probably subclonal (VAF 10%-30%
  * PHE Probably Heterozygote (VAF 30%-40% ou 60%-70%)
  * LHE Likely Heterozygote (VAF 40%-60%) 
  * PHO Probably Homozygote (VAF 70%-80%)
  * LHO Likely Homozygote (VAF > 80%)

  TRC = Total Depth

  RRC = REF depth

  ARC = ALT Depth

  ARR = AF

  SBM = SOR

  SBP = FS

  BRC = TRC - (RRC + ARC)

  BRR = BRC / TRC

  BRE = 1 - BRR

  BKG = Variant quality

  * LCL Likely Clean (BRE 0-20%)
  * PCL Probably Clean (BRE 20%-30%)
  * PNO Probably Noisy (BRE 30%-50%)
  * LNO Likely Noisy (BRE > 80%)

  OLD_MULTIALLELIC = "Original chr:pos:ref:alt encoding"

  OLD_VARIANT = "Original chr:pos:ref:alt encoding"
