rule test_maftools_trinucleotidematrix_mm9:
    input:
        rds = "maf.RDS"
    output:
        tsv = "results/matrix.tsv",
        png = "results/matrix.png",
        rds = "results/matrix.RDS"
    params:
        estimate_extra = "nTry=3"
    wrapper:
        "master/bio/maftools/trinucleotidematrix_mm9"
