name: fq subsample
url: https://github.com/stjude-rust-labs/fq#subsample
description: Outputs a subset of fastq records
authors:
  - Thibault Dayris
input:
  - Path(s) to fastq file(s)
output:
  - Path(s) to subsamples fastq file(s)
params:
  - extra: Optional parameters besides IO
