name: fclones group
url: https://github.com/pkolaczk/fclones
description: Efficient duplicate file finder and remover
authors:
  - Thibault Dayris
input:
  - Path to directory to process
output:
  - Path to duplicates report
params:
  - extra: Optional parameters.
notes: |
  - This wrapper does not modify the file system. It searches for duplicates and report them. There is no danger for your files.

  - The parameter `--format` if automatically provided for csv and json output files.

  - The parameter `--depth` if automatically set to 0 if all input paths are files.

  - The parameter `--symbolic-link` is automatically set if a symbolic link is explicitely given in `snakemake.input`.

  - The parameter `--hidden` is automatically set if a hidden file is explicitely given in `snakemake.input`.
