name: fclones group
url: https://github.com/pkolaczk/fclones
description: Efficient duplicate file finder and remover
authors:
  - Thibault Dayris
input:
  - Path to directory to process
output:
  - Path to duplicates report
params:
  - extra: Optional parameters besides `-t|--threads`
notes: |
  This wrapper does not modify the file system. It searches for duplicates and report
  them. There is no danger for your files.
