from pathlib import Path
import os

workflow_source_dir = Path(os.path.relpath(snakemake.workflow.srcdir(".."), ".")).parent


include: str(workflow_source_dir / "rules" / "000.common.smk")


rule target:
    input:
        unpack(targets)


rule variants_only:
    input:
        multiqc="data_output/MultiQC/Somatic_Variant_Calling.html",
        vcfs=expand("data_output/VCF/{sample}.vcf.gz", sample=sample_list),
        vcf_tbis=expand("data_output/VCF/{sample}.vcf.gz.tbi", sample=sample_list),
        vcf_xlsx=expand("data_output/XLSX/{sample}.xlsx", sample=sample_list),
        vcf_tsv=expand("data_output/TSV/{sample}.tsv", sample=sample_list),
        tmb="data_output/TMB.tsv",
        msi="data_output/MSI.tsv",
        cnv=expand("data_output/CNV/{sample}.tsv", sample=sample_list),


rule cnv_only:
    input:
        cnv=expand("data_output/CNV/{sample}.tsv", sample=sample_list),
        multiqc="data_output/MultiQC/MappingQC.html",


rule tmb_only:
    input:
        tmb="data_output/TMB.tsv",
        multiqc="data_output/MultiQC/Somatic_Variant_Calling.html",


rule msi_only:
    input:
        msi="data_output/MSI.tsv",
        multiqc="data_output/MultiQC/MappingQC.html",


rule mapping_only:
    input:
        multiqc="data_output/MultiQC/MappingQC.html",


rule fusions_only:
    input:
        multiqc="data_output/MultiQC/FusionsQC.html",


#####################
### Final archive ###
#####################


include: str(workflow_source_dir / "rules" / "028.md5.smk")
include: str(workflow_source_dir / "rules" / "024.archive.smk")


###############
### Fusions ###
###############


include: str(workflow_source_dir / "rules"/ "025.star_chimera.smk")
include: str(workflow_source_dir / "rules"/ "026.star_fusions.smk")


###############################
### TSV and Xlsx formatting ###
###############################


include: str(workflow_source_dir / "rules" / "018.vcf2tsv.smk")


#################
### Gather QC ###
#################


include: str(workflow_source_dir / "rules" / "016.mapping_qc.smk")
include: str(workflow_source_dir / "rules" / "017.multiqc.smk")


######################
### MSI sensor pro ###
######################


include: str(workflow_source_dir / "rules" / "022.msisensor.smk")


###########
### TMB ###
###########


include: str(workflow_source_dir / "rules" / "021.tmb.smk")


##################
### CNV Facets ###
##################


include: str(workflow_source_dir / "rules" / "020.cnv_facets.smk")
include: str(workflow_source_dir / "rules" / "023.annot_sv.smk")


###########################
### VCF FILE INDEXATION ###
###########################


include: str(workflow_source_dir / "rules" / "019.tabix.smk")


######################
### VCF annotation ###
######################


include: str(workflow_source_dir / "rules" / "010.snpeff.smk")
include: str(workflow_source_dir / "rules" / "012.snpsift.smk")
include: str(workflow_source_dir / "rules" / "015.occurence.smk")
include: str(workflow_source_dir / "rules" / "011.spliceai.smk")
include: str(workflow_source_dir / "rules" / "013.vcftools.smk")
include: str(workflow_source_dir / "rules" / "014.bigr.annot.smk")


############################################################################
### Correcting Mutect2 :                                                 ###
### AS_FilterStatus: Number=1 and not Number=A which violates VCF format ###
############################################################################

###############################
### Variant calling Mutect2 ###
###############################


include: str(workflow_source_dir / "rules" / "009.gatk.mutect2.smk")


##############################
### GATK BAM RECALIBRATION ###
##############################


include: str(workflow_source_dir / "rules" / "007.gatk.recal.smk")


#####################
### Deduplicating ###
#####################


include: str(workflow_source_dir / "rules" / "006.sambamba.markdup.smk")


# Filter a bam over the capturekit bed file


include: str(workflow_source_dir / "rules" / "005.samtools.filter.smk")


###################
### BWA MAPPING ###
###################


include: str(workflow_source_dir / "rules" / "003.bwa.fixmate.smk")


############################
### FASTP FASTQ CLEANING ###
############################


include: str(workflow_source_dir / "rules" / "002.fastp.trimming.smk")


#################################################
### Gather files from iRODS or mounting point ###
#################################################


include: str(workflow_source_dir / "rules" / "001.bigr_copy.smk")


###########################
### Datasets indexation ###
###########################


include: str(workflow_source_dir / "rules" / "004.sambamba.index.smk")
