rule test_gseDO:
    input:
        rds = "geneList.RDS"
    output:
        rds = "gseDO.RDS",
        tsv = "gseDO.tsv"
    params:
        gseDO_extra = "pvalueCutoff  = 1, pAdjustMethod = 'BH'"
    wrapper:
        "master/bio/clusterProfiler/gseDO"
