rule test_gseDO:
    input:
        rds = "geneList.RDS"
    output:
        rds = "gseDO.RDS",
        tsv = "gseDO.tsv"
    message:
        "Testing enrichDO"
    threads:
        1
    params:
        gseDO_extra = "pvalueCutoff  = 1, pAdjustMethod = 'BH'"
    log:
        "logs/test_gseDO.log"
    wrapper:
        "master/bio/clusterProfiler/gseDO"
