rule test_box_count:
    input:
        counts = "table.tsv"
    output:
        png = "plot.png"
    message:
        "Testing boxp lot of normalized counts"
    threads:
        1
    resources:
        mem_mb = (
            lambda wildcards, attempt: min(attempt * 512, 10240)
        ),
        time_min = (
            lambda wildcards, attempt: min(attempt * 5, 200)
        )
    log:
        "logs/test_box_count.log"
    wrapper:
        "master/bio/seaborn/box-counts"


rule test_box_count_drop_null:
    input:
        counts = "table.tsv"
    output:
        png = "plot_null_dropped.png"
    message:
        "Testing boxp lot of normalized counts"
    threads:
        1
    resources:
        mem_mb = (
            lambda wildcards, attempt: min(attempt * 512, 10240)
        ),
        time_min = (
            lambda wildcards, attempt: min(attempt * 5, 200)
        )
    params:
        drop_null = True
    log:
        "logs/test_box_count.log"
    wrapper:
        "master/bio/seaborn/box-counts"
