rule test_gseDGN:
    input:
        rds = "geneList.RDS"
    output:
        rds = "gseDGN.RDS",
        tsv = "gseDGN.tsv"
    params:
        gseDGN_extra = "pvalueCutoff = 1, pAdjustMethod = 'BH'"
    wrapper:
        "master/bio/clusterProfiler/gseDGN"
