rule test_bioinfokit_heatmap:
    input:
        "hm_cot.csv"
    output:
        "figures/heatmap.png"
    params:
        read_csv = {"index_col": 0},
        hmap = {"rowclus": True}
    wrapper:
        "master/bio/bioinfokit/heatmap"
