from snakemake.utils import min_version

min_version("9.13.1")

configfile: "config.yaml"
print(config)

rule target:
    input:
        expand(
            "tmp/fast5_to_pod5_conversion/{sample}.pod5",
            sample=["SGNex_A549_directcDNA_replicate3_run1"],
        ),


module single_fast5_to_pod5:
    config:
        config
    meta_wrapper:
        "file:.."


use rule * from single_fast5_to_pod5
