from snakemake.utils import min_version

min_version("9.13.1")

container: "docker://quay.io/condaforge/miniforge3:26.5.3-0"

configfile: "config.yaml"


print(config)


rule target:
    input:
        expand(
            "temp/fast5_to_pod5_conversion/{sample}.pod5",
            sample=["SGNex_A549_directcDNA_replicate3_run1"],
        ),


module single_fast5_to_pod5:
    config:
        config
    meta_wrapper:
        "file:.."


use rule * from single_fast5_to_pod5
