rule test_bustools_text:
    input:
        "file.bus",
    output:
        "file.tsv",
    log:
        "logs/bustools.log",
    threads: 1
    params:
        extra="",
    wrapper:
        "master/bio/bustools/text"


rule test_bustools_text_list:
    input:
        ["file.bus", "file2.bus"],
    output:
        "file2.tsv",
    log:
        "logs/bustools.log",
    threads: 1
    params:
        extra="--flags --pad",
    wrapper:
        "master/bio/bustools/text"
