rule replace_bases:
    input:
        "{sample}.rna.fa",
    output:
        "{sample}.dna.fa",
    log:
        "logs/fastaq/replace_bases/test/{sample}.log",
    params:
        old_base="U",
        new_base="T",
    wrapper:
        "master/bio/pyfastaq/replace_bases"
