rule test_forestplot:
    input:
        maf1 = "path/to/maf1.RDS",
        maf2 = "path/to/maf2.RDS"
    output:
        tsv = "path/to/forestplot.tsv",
        png = "path/to/forestPlot.png"
    params:
        compare_extra = "",
        forest_extra = "",
        png_extra = ""
    log:
        "logs/forestplot.log"
    wrapper:
        "master/bio/maftools/forestplot"
