rule test_isoformSwitchAnalyseR__preFilter:
    input:
        switch_list = "switch_list.RDS"
    output:
        rds = "filtered.RDS"
    wrapper:
        "master/bio/isoformSwitchAnalyzeR/preFilter"
