rule test_isoformSwitchAnalyseR_preFilter:
    input:
        switch_list = "switch_list.RDS"
    output:
        rds = "filtered.RDS"
    wrapper:
        "master/bio/isoformSwitchAnalyseR/preFilter"
