rule sim:
    input:
        xg="x.xg",
    output:
        reads="reads/x.seq",
    log:
        "logs/vg/sim/x.log",
    threads: 4
    params:
        "--read-length 100 --num-reads 100 -f",
    wrapper:
        "master/bio/vg/sim"
