rule test_learn_read_orientation_model:
    input:
        f1r2="f1r2.tar.gz"
    output:
        "artifacts-prior.tar.gz"
    log:
        "logs/gatk/learnreadorientationmodel/{sample}.log"
    params:
        extra="",  # optional
        java_opts="", # optional
    # optional specification of memory usage of the JVM that snakemake will respect with global
    # resource restrictions (https://snakemake.readthedocs.io/en/latest/snakefiles/rules.html#resources)
    # and which can be used to request RAM during cluster job submission as `{resources.mem_mb}`:
    # https://snakemake.readthedocs.io/en/latest/executing/cluster.html#job-properties
    resources:
        mem_mb=1024
    wrapper:
        "master/bio/gatk/learnreadorientationmodel"
