rule igv_report:
    input:
        fasta="minigenome.fa",
        vcf="variants.vcf",
        # any number of additional optional tracks, see igv-reports manual
        tracks=["alignments.bam"],
    output:
        "igv-report.html",
    log:
        "logs/igv-report.log",
    params:
        extra="",  # optional params, see igv-reports manual
    wrapper:
        "master/bio/igv-reports"
