name: maf2bed
description: |
  Extract MAF fields to build a BED 3 or 4
author:
  - Thibault Dayris
input:
  - maf: Path to maf file
output:
  - bed3: Optional path to a 3-columned bed file
  - bed4: Optional path to a 4-columned bed file
  - bed6: Optional path to a 6-columned bed file
  - bed9: Optional path to a 9-columned bed file
params:
  - chrom: Name of the chromosome column (default is Chromosome)
  - start: Name of the positional column, aka start mutation (default is Start_Position)
  - end: Name of the reference allele column (default is End_Position)
  - padding: Number of base around the variant to catch (default is 0)
  - gene: Name of the gene symbol/identifier column (default is Hugo_Symbol)
  - strand: Name of the stranding column (default is Strand)
  - score: Name of a score to be associated (default if t_alt_count)