rule test_pcaexplorer_pcaplot:
    input:
        "dst.RDS",
    output:
        "pca.svg",
    log:
        "logs/pca.log",
    params:
        extra="",
        #width=480,
        #height=480,
    wrapper:
        "master/bio/pcaexplorer/pcaplot"
