name: simpleaf index
url: https://simpleaf.readthedocs.io/en/latest/index.html
description: >
  Build Simpleaf (expanded) reference index
authors:
  - Thibault Dayris
input:
  - fasta: Path to fasta file.
  - gtf: Optional path to a GTF/GFF3 file.
  - feature: Optional path to a CSV file containing feature barcode sequences to use for direct reference indexing.
  - probe: Optional path to a CSV file containing probe sequences to use for direct reference indexing.
  - refseq: Optional path to a FASTA file containing reference sequences to directly build index on.
output:
  - Path to index directory
params:
  - extra: Optional parameters for `simpleaf` besides IO, `--workd-dir`, `--gff3-format`, and `--threads`.
notes: >
  If the environment variable `ALEVIN_FRY_HOME` is missing, it will be set to working directory.

  If the file `simpleaf_info.json` is missing, it will be created in the `ALEVIN_FRY_HOME` directory..
