rule strelka:
    input:
        # The normal bam and its index
        # are optional input
        # normal = "data/b.bam",
        # normal_index = "data/b.bam.bai"
        tumor="data/{tumor}.bam",
        tumor_index="data/{tumor}.bam.bai",
        fasta="data/genome.fasta",
        fasta_index="data/genome.fasta.fai",
    output:
        # Strelka output - can be directory or full file path
        directory("{tumor}_vcf"),
    log:
        "logs/strelka_{tumor}.log",
    threads: 1
    params:
        run_extra="",
        config_extra="",
    wrapper:
        "master/bio/strelka/somatic"
