rule vsearch_cluster_fast:
    input:
        cluster_fast="reads/{sample}.fasta",
    output:
        profile="out/cluster_fast/{sample}.profile",
    log:
        "logs/vsearch/cluster_fast/{sample}.log",
        vsearch="out/maskfasta/{sample}.log",
    threads: 1
    params:
        extra="--id 0.2 --sizeout --minseqlength 5",
    wrapper:
        "master/bio/vsearch"


rule vsearch_maskfasta:
    input:
        maskfasta="reads/{sample}.fasta",
    output:
        output="out/maskfasta/{sample}.fasta",
    log:
        "logs/vsearch/maskfasta/{sample}.log",
        vsearch="out/maskfasta/{sample}.log",
    threads: 1
    params:
        extra="--hardmask",
    wrapper:
        "master/bio/vsearch"


rule vsearch_fastx_uniques:
    input:
        fastx_uniques="reads/{sample}.fastq",
    output:
        fastqout="out/fastx_uniques/{sample}.fastq",
    log:
        "logs/vsearch/fastx_uniques/{sample}.log",
        vsearch="out/fastx_uniques/{sample}.log",
    threads: 1
    params:
        extra="--strand both --minseqlength 5",
    wrapper:
        "master/bio/vsearch"


rule vsearch_fastx_uniques_gzip:
    input:
        fastx_uniques="reads/{sample}.fastq",
    output:
        fastqout="out/fastx_uniques/{sample}.fastq.gz",
    log:
        "logs/vsearch/fastx_uniques/{sample}.log",
        vsearch="out/fastx_uniques/{sample}.log",
    threads: 2
    params:
        extra="--strand both --minseqlength 5",
    wrapper:
        "master/bio/vsearch"


rule vsearch_fastx_uniques_bzip2:
    input:
        fastx_uniques="reads/{sample}.fastq",
    output:
        fastqout="out/fastx_uniques/{sample}.fastq.bz2",
    log:
        "logs/vsearch/fastx_uniques/{sample}.log",
        vsearch="out/fastx_uniques/{sample}.log",
    threads: 2
    params:
        extra="--strand both --minseqlength 5",
    wrapper:
        "master/bio/vsearch"


rule vsearch_fastq_convert:
    input:
        fastq_convert="reads/{sample}.fastq",
    output:
        fastqout="out/fastq_convert/{sample}.fastq",
    log:
        "logs/vsearch/fastq_convert/{sample}.log",
        vsearch="out/fastq_convert/{sample}.log",
    threads: 2
    params:
        extra="--fastq_ascii 33 --fastq_asciiout 64",
    wrapper:
        "master/bio/vsearch"


rule vsearch_derep_fulllength:
    input:
        derep_fulllength="reads/{sample}.fasta",
    output:
        output="out/derep_fulllength/{sample}.fasta",
    log:
        "logs/vsearch/derep_fulllength/{sample}.log",
        vsearch="out/derep_fulllength/{sample}.log",
    threads: 2
    params:
        extra="--sizeout --relabel_sha1 --fasta_width 0 --minseqlength 30",
    wrapper:
        "master/bio/vsearch"


rule vsearch_derep_prefix:
    input:
        derep_prefix="reads/{sample}.fasta",
    output:
        output="out/derep_prefix/{sample}.fasta",
    log:
        "logs/vsearch/derep_prefix/{sample}.log",
        vsearch="out/derep_prefix/{sample}.log",
    threads: 2
    params:
        extra="--sizeout --relabel_sha1 --fasta_width 0 --minseqlength 30",
    wrapper:
        "master/bio/vsearch"
