rule test_rbt_vcf_fix_iupac_alleles:
    input:
        "test.vcf",
    output:
        "fixed.bcf",
    log:
        "logs/test_rbt_vcf_fix_iupac_alleles.log",
    threads: 2
    wrapper:
        "master/bio/rbt/vcf_fix_iupac_alleles"


rule test_rbt_vcf_fix_iupac_alleles_io_formats:
    input:
        "fixed.bcf",
    output:
        "fixed.vcf.gz",
    log:
        "logs/test_rbt_vcf_fix_iupac_alleles_io_formats.log",
    threads: 2
    wrapper:
        "master/bio/rbt/vcf_fix_iupac_alleles"
