rule samtools_collate:
    input:
        "mapped/{sample}.bam",
    output:
        "{sample}.collated.bam",
    log:
        "logs/{sample}.log",
    threads: 2
    params:
        extra="-f",
    wrapper:
        "master/bio/samtools/collate"
