rule test_VariantAnnotation_readVcfAsVRange:
    input:
        calls = "calls.vcf.gz",
        tbi = "calls.vcf.gz.tbi"
    output:
        rds = "calls.rds"
    wrapper:
        "master/bio/VariantAnnotation/readVcfAsVRanges"
