rule test_iRODS_imeta:
    output:
        "imeta.txt"
    params:
        extra = "-d",
        kwords = {"projectName": "MetaPRISM", "protocol": "mRNA%"}
    wrapper:
        "master/bio/iRODS/imeta"
