rule whatshap_haplotag:
    input:
        "phased.vcf.gz.tbi",
        "alignment.bam.bai",
        "reference.fasta.fai",
        vcf="phased.vcf.gz",
        aln="alignment.bam",
        ref="reference.fasta",
    output:
        "alignment.phased.bam",
    log:
        "logs/haplotag.10X.phased.log",
    threads: 4
    params:
        extra="",  # optionally use --ignore-linked-read, --tag-supplementary, etc.
    wrapper:
        "master/bio/whatshap/haplotag"
