name: blake b3sum
url: https://github.com/BLAKE3-team/BLAKE3/blob/master/b3sum
description: |
  The official Rust and C implementations of the BLAKE3 cryptographic hash function
authors:
  - Thibault Dayris
input:
  - Path(s) to files to compute hash onto
output:
  - Path to hashes/checks
params:
  - extra: Optional parameters besides IO and threading
