rule test_bedtools_maskfasta:
    input:
        fasta="sequences.fa",
        bed="coordinates.bed"
    output:
        "regenerated.fa"
    params:
        extra=""
    wrapper:
        "master/bio/bedtools/maskfasta"
