rule gatk_clean_sam:
    input:
        bam="{sample}.bam",
    output:
        clean="{sample}.clean.bam",
    log:
        "logs/{sample}.log",
    resources:
        mem_mb=1024,
    params:
        extra="",
        java_opts="",  # optional
    wrapper:
        "master/bio/gatk/cleansam"
