wildcard_constraints:
  species=r"saccharomyces_cerevisiae|homo_sapiens|mus_musculus",
  build=r"R64-1-1|GRCh38|GRCh37|GRCm38|GRCm39",
  release=r"116|75|102|115",
  gxf=r"gtf|gff|gff3",
  seqtype=r"dna|cdna|cds",

configfile: "config/config.yaml"

# Download genome sequences
module download_genome_sequences:
    config:
        config
    meta_wrapper:
        f"{config['repo']}/meta/bio/download_genome_sequences"


use rule * from download_genome_sequences

# Convers single read fast5 to multi-read pod5
module single_fast5_to_pod5:
    config:
        config
    meta_wrapper:
        f"{config['repo']}/meta/bio/single_fast5_to_pod5"


use rule * from single_fast5_to_pod5 

# Align reads on reference
module mapping_dorado_meta:
    config:
        config
    meta_wrapper:
        f"{config['repo']}/meta/bio/mapping_dorado"


use rule * from mapping_dorado_meta

# Call aligned reads
rule target:
    input:
        expand(
            "results/homo_sapiens.GRCh38.116/Dorado.dna/{sample}.bam.bai",
            sample=single_fast5_to_pod5.samples_table.index,
        ),
    default_target: True
