rule test_tar:
    input:
        files_list="files_list.txt",
    output:
        archive="tests.tar.bz2",
    log:
        "test_tar.log",
    params:
        extra="--create",
        explicit_owner=True,
        explicit_group=True,
    wrapper:
        "master/utils/tar"

rule test_untar:
    input:
        archive="tests.tar.bz2",
    output:
        outdir=directory("uncompressed_tests"),
    log:
        "test_untar.log"
    params:
        extra="--extract",
    wrapper:
        "master/utils/tar"        
