rule test_deeptools_alignment_sieve:
    input:
        aln="a.bam",
    output:
        "filtered.bam",
    log:
        "logs/deeptools.log",
    threads: 1
    params:
        extra="",
    wrapper:
        "master/bio/deeptools/alignmentsieve"
