rule genotype_gvcfs:
    input:
        gvcfs=["calls/a.g.vcf", "calls/b.g.vcf"],
        ref="genome.fasta",
    output:
        gvcf="calls/all.g.vcf",
    log:
        "logs/gatk/combinegvcfs.log",
    resources:
        mem_mb=1024,
    params:
        extra="",  # optional
        java_opts="",  # optional
    wrapper:
        "master/bio/gatk/combinegvcfs"
