rule prune:
    input:
        vg="c.vg",
    output:
        pruned="graph/c.pruned.vg",
    log:
        "logs/vg/prune/c.log",
    threads: 4
    params:
        "-r",
    wrapper:
        "master/bio/vg/prune"
