rule test_cooncoplot:
    input:
        maf1 = "path/to/maf1.RDS",
        maf2 = "path/to/maf2.RDS"
    params:
        cooncoplot_extra = "",
        png_extra = "",
    output:
        png = "path/to/cooncoplot.png"
    wrapper:
        "master/bio/maftools/cooncoplot"
