rule test_snpsift_annotate:
    input:
        incall = "in.vcf",
        database = "annotation.vcf"
    output:
        vcf = "annotated/out.vcf"
    message:
        "Testing SnpSift Annotate"
    log:
        "annotate.log"
    wrapper:
        "master/bio/snpsift/annotate"
