name: List available server content
url: https://curl.se/docs/manpage.html
description: >
  This meta-wrapper lists files available on a given server and return a CSV.

  This meta-wrapper includes the following steps:

    +----------+-------+-----------------------------------+
    | Step     | Tool  | Reason                            |
    +==========+=======+===================================+
    | List     | curl  | Get raw list of available data    |
    +----------+------------+------------------------------+
    | Format   | go-yq | Format into CSV                   |
    +----------+-------+-----------------------------------+
    | Format   | xsv   | Add header                        |
    +----------+-------+-----------------------------------+
authors:
  - Thibault Dayris
pathvars:
  default:
    - results
    - logs
    - tmp
