rule test_maftools_cosine_similarity:
    input:
        rds = "signatures.RDS"
    output:
        png = "results/cosine.png",
        tsv = "results/cosine.tsv",
        rds = "results/cosine.RDS"
    params:
        extract_sig_extra = "n=2"
    wrapper:
        "master/bio/maftools/cosine_similarity"
