rule test_deseq2_report:
    input:
        gseapp_tsv = "complete.tsv",
        volcano = "image.png",
        pval_hist = "image.png",
        maplot = "image.png",
        coldata = "coldata.tsv",
        pca = "image.png",
        pca_scree = "image.png",
        pca_corrs = "image.png",
        distro_expr = "image.png"
    output:
        html = "Report.html"
    wrapper:
        "master/bio/deseq2/report"
