rule bamtools_stats:
    input:
        "{sample}.bam",
    output:
        "{sample}.bamstats",
    log:
        "logs/bamtools/stats/{sample}.log",
    params:
        "-insert",  # optional summarize insert size data
    wrapper:
        "master/bio/bamtools/stats"
