rule test_pcaexplorer_distro_expr:
    input:
        dst = "vst.RDS"
    output:
        png = "plot.png"
    message:
        "Testing pcaExplorer distro_expr"
    threads:
        1
    resources:
        mem_mb = (
            lambda wildcards, attempt: min(attempt * 1024, 10240)
        ),
        time_min = (
            lambda wildcards, attempt: min(attempt * 20, 200)
        )
    params:
        extra = "plot_type = 'violin'"
    log:
        "logs/test_pcaexplorer_distro_expr.log"
    wrapper:
        "master/bio/pcaExplorer/distro_expr"
