rule hmmpress_profile:
    input:
        "test-profile.hmm",
    output:
        "test-profile.hmm.h3f",
        "test-profile.hmm.h3i",
        "test-profile.hmm.h3m",
        "test-profile.hmm.h3p",
    log:
        "logs/hmmpress.log",
    threads: 4
    params:
        extra="",
    wrapper:
        "master/bio/hmmer/hmmpress"
