rule test_pandas_deseq2_merge:
    input:
        wald_tsv = "wald.tsv",
        dst_tsv = "dst.tsv",
        gene2gene = "gene2gene.tsv"
    output:
        filtered_counts="filtered_counts.tsv",
        filtered_deseq2="filtered_deseq2.tsv",
        merged_table="merged.tsv"
    log:
        "logs.log"
    wrapper:
        "master/bio/pandas/deseq2_merge"
