rule test_lillipop_plot:
    input:
        maf = "path/to/maf.RDS"
    output:
        png = "path/to/lollipopplot.png"
    params:
        png_extra = "",
        gene = "",
        lollipop_plot_extra = ""
    log:
        "logs/plot.log"
    wrapper:
        "master/maftools/lollipop_plot"
