rule test_cpat_make_hexamer_table:
    input:
        coding = "code.fasta",
        noncoding = "nocode.fasta"
    output:
        "hexamer_table"
    wrapper:
        "master/bio/cpat/make_hexamer_table"
