rule sambamba_sort:
    input:
        "mapped/{sample}.bam",
    output:
        "mapped/{sample}.sorted.bam",
    log:
        "logs/sambamba-sort/{sample}.log",
    threads: 8
    params:
        "",  # optional parameters
    wrapper:
        "master/bio/sambamba/sort"
