rule test_eacon_oncoscan_process:
    input:
        install = "sources",
        ATChannelCel = "{sample}_A.CEL",
        GCChannelCel = "{sample}_C.CEL"
    output:
        rds = "{sample}.RDS"
    wrapper:
        "master/bio/eacon/oncoscan_process"
