---
name: pcaExplorer Annotation
description: Prepare annotation object for pcaExplorer
authors:
  - Thibault Dayris
input:
  - A dds object of all samples and targets
  - A TSV-formated text file containing gene_id, transcript_id and gene_name
output:
  - A RDS file contianing the annotation
notes: |
  This is only used by pcaExplorer and has no other purpose
