rule test_vcf2vcf:
    input:
        vcf="small.vcf",
        fasta="small.fa",
        # Optional input files
        # chain="small.chain",
        # normal_bam="normal.bam",
        tumor_bam="tumor.bam",
    output:
        "corrected.vcf",
    log:
        "test_vcf2vcf.log",
    threads: 1
    params:
        extra=" --new-tumor-id ind2 ",
    wrapper:
        "master/bio/vcf2maf/vcf2vcf"
