rule pandas_merge_salmon_tr:
    input:
        quant = expand("{sample}/quant.sf", sample=["A", "B"]),
        tx2gene = "tx2gene.tsv"
    output:
        tsv = "table_tr_pos.tsv"
    message:
        "Testing pandas merge salmon"
    params:
        header = True,
        position = True
    log:
        "logs/pandas_merge_salmon.log"
    wrapper:
        "master/bio/pandas/salmon"
