rule lofreq:
    input:
        bam="data/{sample}.bam",
        bai="data/{sample}.bai",
    output:
        "calls/{sample}.vcf",
    log:
        "logs/lofreq_call/{sample}.log",
    threads: 8
    params:
        ref="data/genome.fasta",
        extra="",
    wrapper:
        "master/bio/lofreq/call"
