rule salsa2:
    input:
        fas="{sample}.fasta",
        fai="{sample}.fasta.fai",
        bed="{sample}.bed",
    output:
        agp="out/{sample}.agp",
        fas="out/{sample}.fas",
    log:
        "logs/salsa2/{sample}.log",
    resources:
        mem_mb=1024,
    params:
        enzyme="CTTAAG",  # optional
        extra="--clean yes",  # optional
    wrapper:
        "master/bio/salsa2"
