OncoCytoDir: /mnt/beegfs/scratch/bioinfo_core/Oncoscans_Cytoscans/

ref:
  fasta_index: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh37.75/Homo_sapiens.GRCh37.75.dna.primary_assembly.main_chr.fa.fai

jaccard:
  a_overlaps_b: '1E-9'
  b_overlaps_a: '1E-9'
  minimum_overlap_percent: 0.7