rule kallisto_quant:
    input:
        fastq=["reads/{exp}_R1.fastq", "reads/{exp}_R2.fastq"],
        index="index/transcriptome.idx",
    output:
        directory("quant_results_{exp}"),
    log:
        "logs/kallisto_quant_{exp}.log",
    threads: 1
    params:
        extra="--verbose",
    wrapper:
        "master/bio/kallisto/quant"
