rule coverageBed:
    input:
        a="bed/{sample}.bed",
        b="mapped/{sample}.bam",
    output:
        "stats/{sample}.cov",
    log:
        "logs/coveragebed/{sample}.log",
    threads: 8
    params:
        extra="",  # optional parameters
    wrapper:
        "master/bio/bedtools/coveragebed"
