rule test_msisensor_msi:
    input:
        normal="example.normal.bam",
        tumor="example.tumor.bam",
        microsat="example.microsate.sites",
    output:
        "example.msi",
        "example.msi_dis",
        "example.msi_germline",
        "example.msi_somatic",
    log:
        "example.log",
    threads: 1
    params:
        out_prefix="example.msi",
    message:
        "Testing MSIsensor msi"
    wrapper:
        "master/bio/msisensor/msi"
