rule test_collect_sequencing_bias:
    input:
        # Optional bed intervals
        # intervals="",
        # Optional dbSNP
        # dbsnp="",
        bam="mapped/{sample}.bam",
        ref="reference/genome.fasta"
    output:
        "artifacts.pre_adapter_detail_metrics"
    log:
        "logs/gatk/collectsequencingartifactmetrics/{sample}.log"
    params:
        prefix="artifacts" # See notes below
        extra="",  # optional
        java_opts="", # optional
    # optional specification of memory usage of the JVM that snakemake will respect with global
    # resource restrictions (https://snakemake.readthedocs.io/en/latest/snakefiles/rules.html#resources)
    # and which can be used to request RAM during cluster job submission as `{resources.mem_mb}`:
    # https://snakemake.readthedocs.io/en/latest/executing/cluster.html#job-properties
    resources:
        mem_mb=1024
    wrapper:
        "master/bio/gatk/collectsequencingartifactmetrics"
