container: "docker://continuumio/miniconda3:4.4.10"


rule run_metaspades:
    input:
        reads=["test_reads/sample1_R1.fastq.gz", "test_reads/sample1_R2.fastq.gz"],
    output:
        contigs="assembly/contigs.fasta",
        scaffolds="assembly/scaffolds.fasta",
        dir=directory("assembly/intermediate_files"),
    log:
        "log/spades.log",
    benchmark:
        "logs/benchmarks/assembly/spades.txt"
    threads: 8
    resources:
        mem_mb=250000,
    params:
        # all parameters are optional
        k="auto",
        extra="--only-assembler",
    wrapper:
        "master/bio/spades/metaspades"


rule download_test_reads:
    output:
        ["test_reads/sample1_R1.fastq.gz", "test_reads/sample1_R2.fastq.gz"],
    log:
        "log/download.log",
    shell:
        " wget https://zenodo.org/record/3992790/files/test_reads.tar.gz >> {log} 2>&1 ; "
        " tar -xzf test_reads.tar.gz >> {log} 2>&1"
