rule gatk_interval_list_to_bed:
    input:
        intervals="genome.intervals",
    output:
        bed="genome.bed",
    log:
        "logs/genome.log",
    resources:
        mem_mb=1024,
    params:
        extra="",
        java_opts="",  # optional
    wrapper:
        "master/bio/gatk/intervallisttobed"
