rule test_analyze_cpat:
    input:
        switch_list = "switch_list.RDS"
    output:
        rds = "switch_list_consequences.RDS"
    wrapper:
        "master/bio/isoformSwitchAnalyzeR/analyzeSwitchConsequences"
