set-resources:
  reference_ensembl_sequence_download:
    mem_mb: min(attempt * 400, 1500)
    runtime: min(attempt * 30, 240)
  pyfaidx_filter:
    mem_mb: min(attempt * 400, 1500)
    runtime: min(attempt * 30, 240)
  samtools_faidx:
    mem_mb: min(attempt * 400, 1500)
    runtime: min(attempt * 30, 240)
  picard_create_sequence_dictionary:
    mem_mb: min(attempt * 1500, 8000)
    runtime: min(attempt * 30, 240)
  fasta_to_twobit_convert:
    mem_mb: min(attempt * 400, 1500)
    runtime: min(attempt * 30, 240)
  xan_extract_chrom_sizes:
    mem_mb: min(attempt * 400, 1500)
    runtime: min(attempt * 30, 240)


