rule test_snpsift_gmt:
    input:
        vcf = "in.vcf",
        gmt = "fake_set.gmt"
    output:
        vcf = "annotated/out.vcf"
    log:
        "annotate.log"
    wrapper:
        "master/bio/snpsift/geneSets"
