rule test_pyroe_idtoname:
    input:
        "annotation.{format}",
    output:
        "id2name.{format}.tsv",
    log:
        "logs/{format}.log",
    threads: 1
    params:
        extra="",
    wrapper:
        "master/bio/pyroe/idtoname"
