rule bwa_mem:
    input:
        reads=["reads/{sample}.1.fastq", "reads/{sample}.2.fastq"],
        idx=multiext("genome", ".amb", ".ann", ".bwt", ".pac", ".sa"),
    output:
        bam="mapped/{sample}.bam",
        bai="mapped/{sample}.bam.bai",
    log:
        "logs/bwa_mem_sambamba/{sample}.log",
    threads: 8
    params:
        extra=r"-R '@RG\tID:{sample}\tSM:{sample}'",
        sort_extra="",  # Extra args for sambamba.
    wrapper:
        "master/bio/bwa/mem-samblaster"
