rule test_coreutils_sha256sum:
    input:
        "test.rst",
    output:
        "test.sha256sum",
    log:
        "test_coreutils_sha256sum.log",
    threads: 1
    params:
        extra="",
    wrapper:
        "master/utils/coreutils/sha256sum"
