jobs: 30
local-cores: 20
keep-going: true
rerun-triggers: "mtime"
rerun-incomplete: true
shadow-prefix: "tmp/shadow"
report: "report.zip"
report-after-run: true
printshellcmds: true
retries: 2
# show-failed-logs: true
benchmark-extended: true
software-deployment-method:
  - "apptainer"
  - "conda"
executor: "slurm"
latency-wait: 5
slurm-efficiency-report: true
slurm-efficiency-report-path: "benchmark/efficiency_reports"
slurm-efficiency-threshold: 0.9
default-resources:
  - runtime=60
  - mem_mb=1000
  - tmpdir=tmp
  - slurm_account=igr_hpc
