rule test_pandas_hist:
    input:
        tsv = "table.csv"
    output:
        png = "hist.png"
    params:
        extra = {
            "column": "plot"
        }
    wrapper:
        "master/bio/pandas/hist"
