rule pindel2vcf:
    input:
        ref="genome.fasta",
        pindel="pindel/all_{type}",
    output:
        "pindel/all_{type}.vcf",
    log:
        "logs/pindel/pindel2vcf.{type}.log",
    params:
        refname="hg38",  # mandatory, see pindel manual
        refdate="20170110",  # mandatory, see pindel manual
        extra="",  # extra params (except -r, -p, -R, -d, -v)
    wrapper:
        "master/bio/pindel/pindel2vcf"


rule pindel2vcf_multi_input:
    input:
        ref="genome.fasta",
        pindel=["pindel/all_D", "pindel/all_INV"],
    output:
        "pindel/all.vcf",
    log:
        "logs/pindel/pindel2vcf.log",
    params:
        refname="hg38",  # mandatory, see pindel manual
        refdate="20170110",  # mandatory, see pindel manual
        extra="",  # extra params (except -r, -p, -R, -d, -v)
    wrapper:
        "master/bio/pindel/pindel2vcf"
