---
name: BiGR Bulk
description: Perform bulk analysis in IGR Flamingo
authors:
  - Thibault Dayris
input:
  - Fastq files (rnaseq, wes)
output:
  - RNA-Seq-DGE: Quality controls, Quantification
usage:
  - \# Go to your directory containing Fastq files
  - cd /path/to/project
  - \# Copy/paste the following line
  - bash /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/bigr_bulk/run.sh
