name: sopa make test dataset
url: https://gustaveroussy.github.io/sopa/tutorials/api_usage/#create-a-spatialdata-object
description: Creates a toy dataset for sopa
authors:
  - Dayris Thibault
output:
  - Path to dataset directory, the content of the directory depends on the rule parameters.
params:
  - use_blob: Either use SpatialData blob dataset (`True`), or create one with uniformly distributes cells (`False`).
  - extra: Dictionary of optional parameters used to create dataset.
  - write: Dictionary of optional parameters used to write output, despite output path, and over-writing parameter.
notes: |
  Provide arguments throught a dictionnary, not strings.
