rule test_grex:
    input:
        test_cases="cases.txt",
    output:
        "regex.txt",
    log:
        "test_cases.log",
    threads: 1
    params:
        extra="",
    wrapper:
        "master/utils/grex"    
