rule test_variant_occurence_sample:
    input:
        calls=["in.vcf", "in2.vcf"]
    output:
        txt="occurence.{chr}.txt"
    threads: 7
    wrapper:
        "master/bio/variantoccurence/sample"
