rule test_msisensor_table:
    input:
        ["s1.msi", "s2.msi"]
    output:
        "table.msi"
    threads: 1
    params:
        stability=3.5,
        sample_list=["s1", "s2"]
    wrapper:
        "master/bio/BiGR/msisensor_table"