rule test_fclones_group:
    input:
        paths=".",
    output:
        "groups.json",
    log:
        "test_fclones_group.log"
    threads: 1
    params:
        extra="",
    wrapper:
        "master/utils/fclones/group"
