rule test_pcaexplorer_writelaunchscript:
    input:
        dds = "dds.RDS",
        dst = "dst.RDS",
        coldata = "colData.tsv",
        pca2go = "pca2go.RDS",
        annotation = "annot.RDS"
    output:
        script = "pcaExplorer.R"
    wrapper:
        "master/bio/pcaExplorer/writeLaunchScript"
