rule test_rsync:
    input:
        src="Snakefile",
    output:
        dst="Snakefile_copy",
    log:
        "test_rsync.log"
    threads: 1
    params:
        extra="",
    wrapper:
        "master/utils/rsync"
