name: Prepare reference genome files
description: >
  This meta-wrapper includes the following steps:

    +----------------+----------+------------------------------------------------+
    | Step           | Wrapper  | Reason                                         |
    +================+==========+================================================+
    | Download       | Ensembl  | Download reference genome files                |
    +----------------+----------+------------------------------------------------+
    | Clean          | Agat     | Clean GTF/GFF common mistakes, clean genomic   |
    |                |          | elements with low evidence/confidence,         |
    |                |          | ensure all contigs in the GTF/GFF exist in     |
    |                |          | the genome fasta file, and extract CDS.        |
    +----------------+----------+------------------------------------------------+
authors:
  - Thibault Dayris
pathvars:
  default:
    - resources
    - logs
  custom:
    species: Ensembl species code
    build: Ensembl build corresponding to the above species
    release: Ensembl release tag number 

