name: dust
url: https://github.com/bootandy/dust
description: A more intuitive version of `du` in rust
authors:
  - Thibault Dayris
input:
  - path: Optional path or list of paths to given files/directories
  - config: Optional path to a configuration file
output:
  - Path to disk usage tree
params:
  - extra: Optional parameters, besides `-t|--threads`, `--config`, or `-j|--output-json`
notes: |
  An example of `toml` formatted configuration file is available here: 
  https://github.com/bootandy/dust/blob/master/config/config.toml
