rule strling_index:
    input:
        "reference/genome.fasta",
    output:
        index="reference/genome.fasta.str",
        fai="reference/genome.fasta.fai",
    log:
        "log/strling/index.log",
    params:
        extra="",  # optionally add further command line arguments
    wrapper:
        "master/bio/strling/index"
