name: zstd
description: Compress or decompress using Zstandard
url: https://github.com/facebook/zstd
authors:
  - Thibault Dayris
input:
  - Path or list of paths to files to compress or uncompress
output:
  - Path to list of paths to compressed or uncompressed files
params:
  extra: Optional arguments besides `-o`, `--rm`, `--keep`, `-d|--decompress`, `-f|--force`, `-c|--stdout`, `-T`, or `--format`.
notes: |
  Output file names depend on input files.
