rule test_analyze_orf:
    input:
        switch_list = "orf_analyzed_switch_list.RDS"
    output:
        rds = "sequence_extracted_switch_list.RDS"
    wrapper:
        "master/bio/isoformSwitchAnalyzeR/extractSequence"
