rule test_analyze_orf:
    input:
        switch_list = "orf_analyzed_switch_list.RDS"
    output:
        rds = "sequence_extracted_switch_list.RDS",
        fasta = "sequence_extracted_nt.fasta",
        aa_sequence = "sequence_extracted_AA.fasta"
    wrapper:
        "master/bio/isoformSwitchAnalyzeR/extractSequence"
