rule test_fd:
    input:
        ".",
    output:
        "file_list.txt",
    log:
        "test_fd.log",
    threads: 1
    params:
        extra="--hidden",
        pattern="Snakefile"
    wrapper:
        "master/utils/fd-find"
