rule test_analyze_alternative_splicing:
    input:
        switch_list = "switch_list.RDS"
    output:
        "splice_analyzed.RDS"
    wrapper:
        "master/bio/isoformSwitchAnalyzeR/analyzeAlternativeSplicing"
