rule eacon_cytoscan_process:
    input:
        install = "sources",
        cel = "{sample}.CEL",
    output:
        qc_txt = "{sample}/{sample}_2.4.0_{nar}.qc.txt".format(
            sample="{sample}",
            nar=config["params"]["nar"]
        ),
        log = "{sample}/{sample}_2.4.0_{nar}.log".format(
            sample="{sample}",
            nar=config["params"]["nar"]
        ),
        txt = "{sample}/{sample}_CELfile.txt",
        png = "{sample}/{sample}_{arraytype}_{genome}_rawplot.png".format(
            sample="{sample}",
            arraytype=config["params"]["arraytype"],
            genome=config["params"]["genome"]
        ),
        rds = "{sample}/{sample}_{arraytype}_{genome}_processed.RDS".format(
            sample="{sample}",
            genome=config["params"]["genome"],
            arraytype = config["params"]["arraytype"]
        )
    log:
        "logs/EaCoN/{sample}/cytoscan_process.log"
    wrapper:
        "/bio/eacon/cytoscan_process"
