rule test_salmon_decoy:
    input:
        transcriptome = "transcriptome.fasta",
        genome = "genome.fasta"
    output:
        decoys = "decoys.txt",
        gentrome = "gentrome.fasta"
    threads: 2
    wrapper:
        "master/bio/salmon/generate_decoy"
