rule get_regulatory_features_gff3_gz:
    output:
        "resources/regulatory_features.gff3.gz",  # presence of .gz determines if downloaded is kept compressed
    log:
        "logs/get_regulatory_features.log",
    cache: "omit-software"  # save space and time with between workflow caching (see docs); for data downloads, software does not affect the resulting data
    params:
        species="homo_sapiens",  # for available species, release and build, search via "Regulation (GFF)" column at: https://www.ensembl.org/info/data/ftp/index.html
        release="112",
        build="GRCh38",
    wrapper:
        "master/bio/reference/ensembl-regulation"


rule get_regulatory_features_grch37_gff:
    output:
        "resources/regulatory_features.gff",
    log:
        "logs/get_regulatory_features.log",
    cache: "omit-software"  # save space and time with between workflow caching (see docs); for data downloads, software does not affect the resulting data
    params:
        species="homo_sapiens",
        release="112",
        build="GRCh37",
    wrapper:
        "master/bio/reference/ensembl-regulation"


rule get_regulatory_features_mouse_gff_gz:
    output:
        "resources/regulatory_features.mouse.gff.gz",
    log:
        "logs/get_regulatory_features.log",
    cache: "omit-software"  # save space and time with between workflow caching (see docs); for data downloads, software does not affect the resulting data
    params:
        species="mus_musculus",
        release="98",
        build="GRCm39",
    wrapper:
        "master/bio/reference/ensembl-regulation"
