rule test_simplifyenrichment_go:
    input:
        tsv = "go.terms.tsv"
    output:
        png = "simplify.png",
        simplify_rds = "simplify.RDS",
        simplify_tsv = "simplify.tsv",
        similarity_rds = "similarity.RDS",
        similarity_tsv = "similarity.tsv"
    wrapper:
        "master/bio/simplifyenrichment/go"
