rule test_mixcr_assemble:
    input:
        "alignment.vdjca"
    output:
        clones="assembly.clna",
        report="report.txt"
    params:
        extra="-a"
    wrapper:
        "master/bio/mixcr/assemble"
