from snakemake.utils import min_version

min_version("9.13.1")


wildcard_constraints:
    species=r"saccharomyces_cerevisiae",
    build=r"R64-1-1",
    release=r"105",
    datatype=r"dna",


rule target:
    input:
        expand(
            "reference/{species}.{build}.{release}/sequences/{species}.{build}.{release}.dna.{ext}",
            species=["saccharomyces_cerevisiae"],
            build=["R64-1-1"],
            release=[105],
            ext={
                "chrom_sizes.tsv",
                "fasta.fai",
                "dict",
                "fasta",
                "2bit",
            },
        ),


module download_genome_sequences:
    config:
        {
            "pathvars": {
                "tmp": "tmp",
                "benchmark": "benchmark",
                "log": "log",
                "reference": "reference",
            },
            "contigs": ["I", "II"],
        }
    meta_wrapper:
        "file:.."


use rule * from download_genome_sequences
