from snakemake.utils import min_version

min_version("9.13.1")

container: "docker://quay.io/condaforge/miniforge3@sha256:962cf538c4f7b624bac1452a95cc88fb2013a8188445b9b6af85ee748ca5d3c8"

configfile: "config.yaml"


wildcard_constraints:
    species=r"saccharomyces_cerevisiae",
    build=r"R64-1-1",
    release=r"105",
    datatype=r"dna",


rule target:
    input:
        expand(
            "resources/{species}.{build}.{release}/sequences/{species}.{build}.{release}.dna.{ext}",
            species=["saccharomyces_cerevisiae"],
            build=["R64-1-1"],
            release=[105],
            ext={
                "chrom_sizes.tsv",
                "fasta.fai",
                "dict",
                "fasta",
                "2bit",
            },
        ),


module download_genome_sequences:
    config:
        config
    meta_wrapper:
        "file:.."


use rule * from download_genome_sequences
