from snakemake.utils import min_version

min_version("9.13.1")

container: "docker://quay.io/condaforge/miniforge3:26.5.3-0"
shell.executable("/bin/bash")

configfile: "config.yaml"


wildcard_constraints:
    species=r"saccharomyces_cerevisiae",
    build=r"R64-1-1",
    release=r"105",
    datatype=r"dna",


rule target:
    input:
        expand(
            "resources/{species}.{build}.{release}/sequences/{species}.{build}.{release}.dna.{ext}",
            species=["saccharomyces_cerevisiae"],
            build=["R64-1-1"],
            release=[105],
            ext={
                "chrom_sizes.tsv",
                "fasta.fai",
                "dict",
                "fasta",
                "2bit",
            },
        ),
        mat_n_met="resources/saccharomyces_cerevisiae.R64-1-1.105/sequences/Genome_sequences_material_and_methods.html",


module download_genome_sequences:
    config:
        config
    meta_wrapper:
        f"{config['repo']}/meta/bio/download_genome_sequences"


use rule * from download_genome_sequences
