rule bgzip:
    input:
        "{prefix}.vcf",
    output:
        "{prefix}.vcf.gz",
    log:
        "logs/bgzip/{prefix}.log",
    threads: 1
    params:
        extra="",  # optional
    wrapper:
        "master/bio/bgzip"
