name: Ensembl variations
description: >
  Download, fix, and filter Ensembl variations
  
    +-------------+-----------+-----------------------------------------------------+
    | Step        | Tool      | Reason                                              |
    +=============+===========+=====================================================+
    | Download    | curl      | Download genome sequence from Ensembl               |
    +-------------+-----------+-----------------------------------------------------+
    | Fix         | rbt       | Fix common Ensembl format issues on GFF files       |
    +-------------+-----------+-----------------------------------------------------+
    | Filter      | bcftools  | Ensure same contigs are present in Fasta/VCF files  |
    +-------------+-----------+-----------------------------------------------------+
authors:
  - Thibault Dayris
pathvars:
  default:
    - resources
    - results
    - logs
  custom:
    - genome sequence index (`.fasta.fai`)
