rule splitncigarreads:
    input:
        bam="mapped/{sample}.bam",
        ref="genome.fasta",
    output:
        "split/{sample}.bam",
    log:
        "logs/gatk/splitNCIGARreads/{sample}.log",
    resources:
        mem_mb=1024,
    params:
        extra="",  # optional
        java_opts="",  # optional
    wrapper:
        "master/bio/gatk/splitncigarreads"
