rule bedtools_intersect:
    input:
        left="A.bed",
        right="B.bed",
    output:
        "A_B.intersected.bed",
    log:
        "logs/intersect/A_B.log",
    params:
        ## Add optional parameters 
        extra="-wa -wb",  ## In this example, we want to write original entries in A and B for each overlap.
    wrapper:
        "master/bio/bedtools/intersect"


rule bedtools_intersect_gz:
    input:
        left="A.bed",
        right="B.bed",
    output:
        "A_B.intersected.bed.gz",
    log:
        "logs/intersect/A_B_gz.log",
    params:
        ## Add optional parameters 
        extra="-wa -wb",  ## In this example, we want to write original entries in A and B for each overlap.
    wrapper:
        "master/bio/bedtools/intersect"
