rule test_eacon_ascn:
    input:
        rds = "{sample}/ASCAT/L2R/{sample}.SEG.ASCAT.RDS"
    output:
        gamma_eval = multiext(
            "{sample}/ASCAT/ASCN/{sample}.gemmeEval",
            ".png",
            ".txt"
        )
    wrapper:
        "master/bio/eacon/ascn"
