rule lofreq_uniform_indelqual:
    input:
        bam="data/{sample}.bam",
    output:
        "out/indelqual/{sample}.uindel.bam",
    log:
        "logs/{sample}.uindel.log",
    threads: 8
    params:
        extra="-u 15",
    wrapper:
        "master/bio/lofreq/indelqual"


rule lofreq_dindel_indelqual:
    input:
        bam="data/{sample}.bam",
        ref="data/hg38_chr21.fa",
    output:
        "out/indelqual/{sample}.dindel.bam",
    log:
        "logs/{sample}.dindel.log",
    threads: 8
    params:
        extra="--dindel",
    wrapper:
        "master/bio/lofreq/indelqual"
