rule scaffold:
    input:
        query="fasta/{query}.fasta",
        ref="fasta/{reference}.fasta",
    output:
        fasta="{query}_scaffold_{reference}/ragtag.scaffold.fasta",
        agp="{query}_scaffold_{reference}/ragtag.scaffold.agp",
        stats="{query}_scaffold_{reference}/ragtag.scaffold.stats",
    log:
        "logs/ragtag/{query}_scaffold_{reference}.log",
    threads: 16
    params:
        extra="",
    wrapper:
        "master/bio/ragtag/scaffold"
