rule tx_to_gene:
    input:
        gtf = "file.gtf"
    output:
        tsv = "tx2gene.tsv"
    message:
        "Testing tx_to_gene"
    threads:
        1
    resources:
        mem_mb = (
            lambda wildcards, attempt: min(attempt * 512, 1024)
        ),
        time_min = (
            lambda wildcards, attempt: min(attempt * 10, 15)
        )
    log:
        "logs/tx_to_gene.log"
    wrapper:
        "master/bio/tx_to_gene/gtf"
