rule seqkit_seq:
    input:
        fasta="data/{sample}.fa",
    output:
        fasta="out/seq/{sample}.fa.gz",
    log:
        "logs/seq/{sample}.log",
    threads: 2
    params:
        command="seq",
        extra="--min-len 10",
    wrapper:
        "master/bio/seqkit"


rule seqkit_subseq_bed:
    input:
        fasta="data/{sample}.fa",
        bed="data/{sample}.bed",
    output:
        fasta="out/subseq/bed/{sample}.fa.gz",
    log:
        "logs/subseq/bed/{sample}.log",
    threads: 2
    params:
        command="subseq",
    wrapper:
        "master/bio/seqkit"


rule seqkit_subseq_gtf:
    input:
        fasta="data/{sample}.fa",
        gtf="data/{sample}.gtf",
    output:
        fasta="out/subseq/gtf/{sample}.fa.gz",
    log:
        "logs/subseq/gtf/{sample}.log",
    threads: 2
    params:
        command="subseq",
        extra="--feature CDS",
    wrapper:
        "master/bio/seqkit"


rule seqkit_subseq_region:
    input:
        fasta="data/{sample}.fa",
    output:
        fasta="out/subseq/region/{sample}.fa.gz",
    log:
        "logs/subseq/region/{sample}.log",
    threads: 2
    params:
        command="subseq",
        extra="--region 1:12",
    wrapper:
        "master/bio/seqkit"


rule seqkit_fx2tab:
    input:
        fastx="data/{sample}.fastq",
    output:
        tsv="out/fx2tab/{sample}.tsv",
    log:
        "logs/fx2tab/{sample}.log",
    threads: 2
    params:
        command="fx2tab",
        extra="--name",
    wrapper:
        "master/bio/seqkit"


rule seqkit_grep_name:
    input:
        fastx="data/{sample}.fastq",
        pattern="data/name.txt",
    output:
        fastx="out/grep/name/{sample}.fastq.gz",
    log:
        "logs/grep/name/{sample}.log",
    threads: 2
    params:
        command="grep",
        extra="--by-name",
    wrapper:
        "master/bio/seqkit"


rule seqkit_grep_seq:
    input:
        fastx="data/{sample}.fastq",
        pattern="data/seq.txt",
    output:
        fastx="out/grep/seq/{sample}.fastq.gz",
    log:
        "logs/grep/seq/{sample}.log",
    threads: 2
    params:
        command="grep",
        extra="--by-seq",
    wrapper:
        "master/bio/seqkit"


rule seqkit_rmdup_name:
    input:
        fastx="data/{sample}.fastq",
    output:
        fastx="out/rmdup/name/{sample}.fastq.gz",
        dup_num="out/rmdup/name/{sample}.num.txt",
        dup_seqs="out/rmdup/name/{sample}.seq.txt",
    log:
        "logs/rmdup/name/{sample}.log",
    threads: 2
    params:
        command="rmdup",
        extra="--by-name",
    wrapper:
        "master/bio/seqkit"


rule seqkit_rmdup_seq:
    input:
        fastx="data/{sample}.fastq",
    output:
        fastx="out/rmdup/seq/{sample}.fastq.gz",
        dup_num="out/rmdup/seq/{sample}.num.txt",
        dup_seqs="out/rmdup/seq/{sample}.seq.txt",
    log:
        "logs/rmdup/seq/{sample}.log",
    threads: 2
    params:
        command="rmdup",
        extra="--by-seq",
    wrapper:
        "master/bio/seqkit"


rule seqkit_stats:
    input:
        fastx="data/{sample}.fastq",
    output:
        stats="out/stats/{sample}.tsv",
    log:
        "logs/stats/{sample}.log",
    threads: 2
    params:
        command="stats",
        extra="--all --tabular",
    wrapper:
        "master/bio/seqkit"


rule seqkit_common:
    input:
        fastas=[
            "data/{sample1}.fa",
            "data/{sample2}.fa",
        ],
    output:
        fasta="out/common/{sample1}_{sample2}.fa.gz",
    log:
        "logs/common/{sample1}_{sample2}.log",
    threads: 2
    params:
        command="common",
        extra="",
    wrapper:
        "master/bio/seqkit"


rule seqkit_concat:
    input:
        fastas=[
            "data/{sample1}.fa",
            "data/{sample2}.fa",
        ],
    output:
        fasta="out/concat/{sample1}_{sample2}.fa.gz",
    log:
        "logs/concat/{sample1}_{sample2}.log",
    threads: 2
    params:
        command="concat",
        extra="",
        out_bgzip=True,
    wrapper:
        "master/bio/seqkit"


rule seqkit_split2_part:
    input:
        fasta="data/{sample}.fa",
    output:
        fasta=[
            "out/split2/part/{sample}.1-of-2.fas",
            "out/split2/part/{sample}.2-of-2.fas",
        ],
    log:
        "logs/split/part/{sample}.log",
    threads: 2
    params:
        command="split2",
        extra="--by-part 2",
    wrapper:
        "master/bio/seqkit"
