rule samtools_fastq_interleaved:
    input:
        "mapped/{sample}.bam",
    output:
        "reads/{sample}.fq",
    log:
        "{sample}.interleaved.log",
    threads: 3
    params:
        " ",
    wrapper:
        "master/bio/samtools/fastq/interleaved"
