rule test_cibersort_abs:
    input:
        quant="quantification.tsv"
    output:
        histogram="celltypes.hist.png",
        dotplot="celltypes.dotplot.png",
        tsv="celltypes.tsv",
        rds="celltypes.RDS"
    params:
        cibersort_binary="/path/to/cibersort/non/free",
        cibersort_mat="/path/to/celltypes.mat"
    wrapper:
        "master/bio/immunedeconv/cibersort-abs"
