rule test_deseq2_to_genelist:
    input:
        rds = "dds.RDS"
    output:
        gene_lists = directory("geneLists")
    message:
        "Testing geneList creation from DESeq2 output"
    threads:
        1
    resources:
        mem_mb = (
            lambda wildcards, attempt: min(attempt * 1024, 10240)
        ),
        time_min = (
            lambda wildcards, attempt: min(attempt * 20, 200)
        )
    log:
        "logs/test_deseq2_to_genelist.log"
    wrapper:
        "master/bio/clusterProfiler/DESeq2_to_geneList"
