rule bamtools_filter_json:
    input:
        "{sample}.bam",
    output:
        "filtered/{sample}.bam",
    log:
        "logs/bamtools/filtered/{sample}.log",
    params:
        json="filtering-rules.json",
        region="",  # optional parameter for defining a specific region, e.g. "chr1:500..chr3:750"
    wrapper:
        "master/bio/bamtools/filter_json"
