from snakemake.utils import min_version

min_version("9.13.1")

container: "docker://quay.io/condaforge/miniforge3:26.5.3-0"

configfile: "config.yaml"


wildcard_constraints:
    species=r"saccharomyces_cerevisiae",
    build=r"R64-1-1",
    release=r"105",
    gfx=f"gtf|gff3",


rule target:
    input:
        expand(
            "resources/{species}.{build}.{release}/annotations/{species}.{build}.{release}.{gxf}",
            species=["saccharomyces_cerevisiae"],
            build=["R64-1-1"],
            release=[105],
            gxf={"gtf", "gff3"},
        ),
        mat_n_met="resources/saccharomyces_cerevisiae.R64-1-1.105/annotations/Genome_annotation_material_and_methods.html",


module download_genome_annotation:
    config:
        config
    meta_wrapper:
        "file:.."


use rule * from download_genome_annotation
