from snakemake.utils import min_version

min_version("9.13.1")


wildcard_constraints:
    species=r"saccharomyces_cerevisiae",
    build=r"R64-1-1",
    release=r"105",
    gfx=f"gtf|gff",


rule target:
    input:
        expand(
            "reference/{species}.{build}.{release}/annotations/{species}.{build}.{release}.{gxf}",
            species=["saccharomyces_cerevisiae"],
            build=["R64-1-1"],
            release=[105],
            gxf={"gtf", "gff"},
        ),


module download_genome_annotation:
    config:
        {
            "pathvars": {
                "tmp": "tmp",
                "benchmark": "benchmark",
                "log": "log",
                "reference": "reference",
                "genome_sequence": "genome.fasta",
            }
        }
    meta_wrapper:
        "file:.."


use rule * from download_genome_annotation
