rule test_biomart_mouse_to_human:
    input:
        mouse = "test_table.tsv"
    output:
        translated = "translated_table.tsv"
    params:
        mgi_id = "Hugo_ID"
    wrapper:
        "master/bio/biomaRt/mouse_to_human"
