rule genomics_db_import:
    input:
        gvcfs=["calls/a.g.vcf.gz", "calls/b.g.vcf.gz"],
    output:
        db=directory("db"),
    log:
        "logs/gatk/genomicsdbimport.log",
    threads: 2
    resources:
        mem_mb=lambda wildcards, input: max([input.size_mb * 1.6, 200]),
    params:
        intervals="ref",
        db_action="create",  # optional
        extra="",  # optional
        java_opts="",  # optional
    wrapper:
        "master/bio/gatk/genomicsdbimport"
