from snakemake.utils import min_version

min_version("9.13.1")


configfile: "config.yaml"


module gatk_mutect2_calling:
    config:
        config
    meta_wrapper:
        "file:.."


use rule * from gatk_mutect2_calling
