rule tx_to_gene:
    input:
        gtf = "file.gtf"
    output:
        tx2gene = "tx2gene.tsv",
        tx2gene_large = "tx2gene_with_positions.tsv",
        gene2gene = "gene2gene.tsv",
        gene2gene_large = "gene2gene_with_chr.tsv"
    message:
        "Testing tx_to_gene"
    threads:
        1
    resources:
        mem_mb = (
            lambda wildcards, attempt: min(attempt * 512, 1024)
        ),
        time_min = (
            lambda wildcards, attempt: min(attempt * 10, 15)
        )
    log:
        "logs/tx_to_gene.log"
    wrapper:
        "master/bio/gtf/tx2gene"
