rule rootcp:
    input:
        "ntuple0.root",
    output:
        "ntuple0_copy.root",
    log:
        "logs/rootcp/rootcp.log",
    threads: 1
    params:
        input_object_name="TestTree",
        extra="--recreate",
    wrapper:
        "master/phys/root/rootcp"
