rule test_clusterprofiler_bitr:
    input:
        table = "table.tsv"
    output:
        rds = "geneList.RDS",
        translation_table = "complete_table.tsv"
    wrapper:
        "master/bio/clusterProfiler/bitr_GRCh38"
