rule test_clusterprofiler_enrichplot:
    input:
        rds="gsea.RDS"
    output:
        # barplot="barplot.png",
        # dotplot="dotplot.png",
        # cnetplot="cntplot.png",
        # heatplot="heatplot.png",
        # emapplot="emapplot.png",
        upsetplot="upsetplot.png",
        # pmcplot="pmcplot.png",
    threads: 1
    log:
        "logs/clusterprofiler.log"
    params:
        enricher_extra="pvalueCutoff = 1, qvalueCutoff = 1",
        barplot_extra="showCategory = 2",
        dotplot_extra="showCategory = 2",
        cnetplot_extra="showCategory = 2",
        heatplot_extra="showCategory = 2",
        emapplot_extra="showCategory = 2",
        upsetplot_extra="n = 2",
        pmcplot_extra="period=2010:2020",
        png_extra="height = 480, width = 480, units = 'px'",
    wrapper:
        "master/bio/clusterprofiler/enrichplot"