name: rsync
url: https://github.com/RsyncProject/rsync/
description: |
  An open source utility that provides fast incremental file transfer. It also has 
  useful features for backup and restore operations among many other use cases.
author:
  - Thibault Dayris
input:
  - src: Path(s) to file(s) to transfer
  - exclude: Optional path to read exclude patterns
  - include: Optional path to read include patterns
  - from: Path to read list of source-file names.
  - password: Optional path to read daemon-access password
  - early_input: Optional path to daemon's early exec input
  - config: Optional path to alternate rsyncd.conf file
output:
  - dst: Path(s) to destination file(s)
  - log: Optional path to internal log file
  - batch: Optional path to a batched update file
  - wo_batch: Optional path to a batched update file for write only
  - read_batch: Optional path to a batched update file for read only
params:
  - extra: Optional parameters besides IO and threading
notes: |
  Please note that `input.src` and `input.from` are mutually exclusive.
