rule test_msisensor_scan:
    input:
        "genome.fasta"
    output:
        "microsat.list"
    threads:
        1
    params:
        extra = ""
    log:
        "logs/msisensor_scan.log"
    wrapper:
        "master/bio/msisensor_pro/scan"
