rule test_simpleaf_add_chemistry:
    output:
        "custom_chemistries.json"
    threads: 1
    log:
        "logs/chemistry.log"
    params:
        name="10xCustom",
        geometry="1{b[16]u[12]x:}2{r:}",
    wrapper:
        "master/bio/simpleaf/addchemistry"