rule vg_autoindex_giraffe:
    input:
        ref="{genome}.fasta",
        # Optional vcf file containing haplotypes for graph creation
        #vcf="",
    output:
        multiext(
            "resources/{genome}",
            ".dist",
            ".shortread.zipcodes",
            ".shortread.withzip.min",
            ".giraffe.gbz",
        ),
    log:
        "logs/autoindex/{genome}.log",
    threads: 8
    params:
        extra="",
    wrapper:
        "master/bio/vg/autoindex"


rule vg_autoindex_map:
    input:
        ref="{genome}.fasta",
        # Optional vcf file containing haplotypes for graph creation
        #vcf="",
    output:
        multiext("resources/{genome}", ".xg", ".gcsa", ".gcsa.lcp"),
    log:
        "logs/autoindex/{genome}.log",
    threads: 8
    params:
        extra="",
    wrapper:
        "master/bio/vg/autoindex"
