rule hmmbuild_profile:
    input:
        "test-profile.sto",
    output:
        "test-profile.hmm",
    log:
        "logs/test-profile-hmmbuild.log",
    threads: 4
    params:
        extra="",
    wrapper:
        "master/bio/hmmer/hmmbuild"
