repo: "file:../../"
samples_table: "config/samples.csv"
pathvars:
  sample: "{sample}"
  species: "{species}"
  build: "{build}"
  release: "{release}"
  seqtype: "dna"
  genome_sequence: "<resources>/{species}.{build}.{release}/sequences/{species}.{build}.{release}.dna.fasta"
  genome_sequence_index: "<resources>/{species}.{build}.{release}/sequences/{species}.{build}.{release}.dna.fasta.fai"

species_build_release:
  - "saccharomyces_cerevisiae.R64-1-1.115"
  - "homo_sapiens.GRCh38.116"
  - "homo_sapiens.GRCh37.75"
  - "mus_musculus.GRCm38.102"
  - "mus_musculus.GRCm39.116"


homo_sapiens:
  cannonical_chromosomes:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - "X"
    - "Y"
    - "MT"


mus_musculus:
  cannonical_chromosomes:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - "X"
    - "Y"
    - "MT"

saccharomyces_cerevisiae:
  cannonical_chromosomes:
    - "I"
    - "II"
    - "III"
    - "IV"
    - "V"
    - "VI"
    - "VII"
    - "IX"
    - "X"
    - "XI"
    - "XII"
    - "XIII"
    - "XIV"
    - "XV"
    - "XVI"
    - "MT"


