rule test_msigdb_gsea:
    input:
        rds = "geneList.RDS"
    output:
        rds = "msigdb_gsea.RDS",
        tsv = "msigdb_gsea.tsv"
    message:
        "Testing enrichDO"
    threads:
        1
    log:
        "logs/test_msigdb_gsea.log"
    wrapper:
        "master/bio/clusterProfiler/msigdb_gsea"
