name: single fast5 to pod5
url: https://github.com/nanoporetech/ont_fast5_api
description: >
  This meta-wrapper downloads fast5 archives, untar them, convert them into pod5

  This meta-wrapper includes the following steps:

    +----------+---------------+-------------------------------------+
    | Step     | Tool          | Reason                              |
    +==========+===============+=====================================+
    | Download | aria2c        | Get single-fast5 archive            |
    +----------+---------------+-------------------------------------+
    | Concat   | ont_fast5_api | Convert single-fast5 to multi-fast5 |
    +----------+---------------+-------------------------------------+
    | Format   | pod5          | Convert multi-fast5 to pod5         |
    +----------+---------------+-------------------------------------+
authors:
  - Thibault Dayris
pathvars:
  default:
    - results
    - logs
    - tmp
