rule test_bedtools_complement:
    input:
        intervals = "intervals.bed",
        genome = "small.genome"
    output:
        "complement.bed"
    message:
        "Testing bedtools complement"
    threads:
        1
    resources:
        mem_mb = (
            lambda wildcards, attempt: min(attempt * 1024, 10240)
        ),
        time_min = (
            lambda wildcards, attempt: min(attempt * 20, 200)
        )
    log:
        "logs/test_bedtools_complement.log"
    wrapper:
        "master/bio/bedtools/complement"
