rule bedtools_complement_bed:
    input:
        in_file="a.bed",
        genome="dummy.genome",
    output:
        "results/bed-complement/a.complement.bed",
    log:
        "logs/a.complement.bed.log",
    params:
        ## Add optional parameters
        extra="-L",
    wrapper:
        "master/bio/bedtools/complement"


rule bedtools_complement_bed_gz:
    input:
        in_file="a.bed",
        genome="dummy.genome",
    output:
        "results/bed-complement/a.complement.bed.gz",
    log:
        "logs/a.complement.bed.gz.log",
    params:
        ## Add optional parameters
        extra="-L",
    wrapper:
        "master/bio/bedtools/complement"


rule bedtools_complement_vcf:
    input:
        in_file="a.vcf",
        genome="dummy.genome",
    output:
        "results/vcf-complement/a.complement.vcf",
    log:
        "logs/a.complement.vcf.log",
    params:
        ## Add optional parameters
        extra="-L",
    wrapper:
        "master/bio/bedtools/complement"
