rule haplotype_caller:
    input:
        # single or list of bam files
        bam="mapped/{sample}.bam",
        ref="genome.fasta",
        # known="dbsnp.vcf"  # optional
    output:
        vcf="calls/{sample}.vcf",
    # 	bam="{sample}.assemb_haplo.bam",
    log:
        "logs/gatk/haplotypecaller/{sample}.log",
    threads: 4
    resources:
        mem_mb=1024,
    params:
        extra="",  # optional
        java_opts="",  # optional
    wrapper:
        "master/bio/gatk/haplotypecaller"


rule haplotype_caller_gvcf:
    input:
        # single or list of bam files
        bam="mapped/{sample}.bam",
        ref="genome.fasta",
        # known="dbsnp.vcf"  # optional
    output:
        gvcf="calls/{sample}.g.vcf",
    # 	bam="{sample}.assemb_haplo.bam",
    log:
        "logs/gatk/haplotypecaller/{sample}.log",
    threads: 4
    resources:
        mem_mb=1024,
    params:
        extra="",  # optional
        java_opts="",  # optional
    wrapper:
        "master/bio/gatk/haplotypecaller"
