set-resources:
  reference_ensembl_annotation_download:
    googlebatch_memory: min(attempt * 400, 1500)
    googlebatch_max_run_duration: str(min(attempt * 30 * 60, 240 * 60)) + "s"
    googlebatch_boot_disk_gb: max(30, 6 * attempt)
    googlebatch_machine_type: "e2-micro"

  agat_default_config:
    googlebatch_memory: min(attempt * 400, 1500)
    googlebatch_max_run_duration: str(min(attempt * 30 * 60, 240 * 60)) + "s"
    googlebatch_boot_disk_gb: max(30, 6 * attempt)
    googlebatch_machine_type: "e2-micro"

  go_yq_update_gff_config:
    googlebatch_memory: min(attempt * 400, 1500)
    googlebatch_max_run_duration: str(min(attempt * 30 * 60, 240 * 60)) + "s"
    googlebatch_boot_disk_gb: max(30, 6 * attempt)
    googlebatch_machine_type: "e2-micro"

  go_yq_update_gtf_config:
    googlebatch_memory: min(attempt * 400, 1500)
    googlebatch_max_run_duration: str(min(attempt * 30 * 60, 240 * 60)) + "s"
    googlebatch_boot_disk_gb: max(30, 6 * attempt)
    googlebatch_machine_type: "e2-micro"

  agat_convert_sp_gxf2gxf:
    googlebatch_memory: min(attempt * 9000, 30000)
    googlebatch_max_run_duration: str(min(attempt * 30 * 60, 240 * 60)) + "s"
    googlebatch_boot_disk_gb: max(30, 6 * attempt)
    googlebatch_machine_type: "e2-micro"

  agat_sq_filter_feature_from_fasta:
    googlebatch_memory: min(attempt * 9000, 30000)
    googlebatch_max_run_duration: str(min(attempt * 30 * 60, 240 * 60)) + "s"
    googlebatch_boot_disk_gb: max(30, 6 * attempt)
    googlebatch_machine_type: "e2-micro"

  agat_sp_filter_feature_by_attribute_value: 
    googlebatch_memory: min(attempt * 9000, 30000)
    googlebatch_max_run_duration: str(min(attempt * 30 * 60, 240 * 60)) + "s"
    googlebatch_boot_disk_gb: max(30, 6 * attempt)
    googlebatch_machine_type: "e2-micro"
