rule test_mixcr_align:
    input:
        "sequences.fastq"
    output:
        vdjca = "alignment.vdjca",
        report = "alignment.txt"
    params:
        species = "hs",
        extra = "-OvParameters.geneFeatureToAlign=VGeneWithP -OsaveOriginalReads=true"
    wrapper:
        "master/bio/mixcr/align"
