rule test_split_vcf_features:
    input:
        call = "mouse.vcf"
    output:
        call = "mouse.split.vcf"
    log:
        "logs/mouse.log"
    wrapper:
        "master/bio/BiGR/split_vcf_features"
