from snakemake.utils import min_version

min_version("9.13.1")


configfile: "config.yaml"


module ensembl_reference:
    meta_wrapper:
        "file:.."
    config:
        config


use rule * from ensembl_reference
