rule test_bustools_sort:
    input:
        "file.bus",
    output:
        "sorted.bus",
    log:
        "bustools.log",
    threads: 1
    resources:
        mem_mb=765,
    params:
        extra="--umi",
    wrapper:
        "master/bio/bustools/sort"
