rule test_revel_to_vcf:
    input:
        db = "path/to/revel/db.tsv"
    output:
        vcf = "path/to/revel.vcf"
    threads: 1
    log:
        "logs/revel/tovcf.log"
    wrapper:
        "master/bio/reve/tovcf"
