rule test_docutils_rst2html:
    input:
        rst="test.rst",
    output:
        html="test.html",
    log:
        "test_docutils_rst2html.log",
    threads: 1
    params:
        extra="--embed-stylesheet",
    wrapper:
        "master/utils/docutils/rst2html"
