rule test_volcano:
    input:
        deseq2_tsv = "diff.tsv"
    output:
        png = "Volcano.png"
    log:
        "logs/test_volcano.log"
    wrapper:
        "master/bio/enhancedVolcano/volcano-deseq2"
