rule test_snpsift_gwascat:
    input:
        vcf = "in.vcf",
        gwascat = "gwascatalog.txt"
    output:
        vcf = "annotated/out.vcf"
    message:
        "Testing SnpSift GWAS catalog annotation"
    log:
        "annotate.log"
    wrapper:
        "master/bio/snpsift/gwasCat"
