rule FilterConsensusReads:
    input:
        "mapped/{sample}.bam",
    output:
        "mapped/{sample}.filtered.bam",
    log:
        "logs/fgbio/filterconsensusreads/{sample}.log",
    threads: 1
    params:
        extra="",
        min_base_quality=2,
        min_reads=[2, 2, 2],
        ref="genome.fasta",
    wrapper:
        "master/bio/fgbio/filterconsensusreads"
