rule gene_length:
    input:
        gtf = "file.gtf"
    output:
        tsv = "genelength.tsv"
    message:
        "Testing gene_length wrapper"
    threads:
        1
    resources:
        mem_mb = (
            lambda wildcards, attempt: min(attempt * 512, 1024)
        ),
        time_min = (
            lambda wildcards, attempt: min(attempt * 10, 15)
        )
    params:
        header = True,
        positions = True
    log:
        "logs/gene_length.log"
    wrapper:
        "master/bio/gtf/gene_length"
