rule test_treeplot:
    input:
        rds = "gene_list.RDS",
    output:
        png = "treeplot.png",
    params:
        extra_paiwise_termism = "",
        extra_treeplot = "",
    log:
        "logs/treeplot.log"
    wrapper:
        "master/bio/clusterProfiler/treeplot"
