rule sambamba_view:
    input:
        "mapped/{sample}.bam",
    output:
        "mapped/{sample}.filtered.bam",
    log:
        "logs/sambamba-view/{sample}.log",
    threads: 8
    params:
        extra="-f bam -F 'mapping_quality >= 50'",  # optional parameters
    wrapper:
        "master/bio/sambamba/view"
