---
name: rlog
authors:
  - Thibault Dayris
description: Apply a rlog transformation on deseq2 datasets
input:
  - A DESeq2 dataset as a RDS file
output:
  - A RDS file of the DDS object with rlog transform
  - A TSV-formatted text file contianing the normalized count table
