rule printreads:
    input:
        bam="{sample}.bam",
        bai="{sample}.bai",
        #        recal_data="{sample}.recal_data_table",
        ref="genome.fasta",
        fai="genome.fasta.fai",
        dict="genome.dict",
    output:
        bam="{sample}.bqsr.bam",
        bai="{sample}.bqsr.bai",
    log:
        "logs/gatk/bqsr/{sample}.log",
    threads: 16
    resources:
        mem_mb=1024,
    params:
        extra="--defaultBaseQualities 20 --filter_reads_with_N_cigar",  # optional
    wrapper:
        "master/bio/gatk3/printreads"
