ref:
  fasta: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.fasta
  fasta_idx: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.fasta.fai
  fasta_dict: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.dict
  vep: /mnt/beegfs/database/bioinfo/vep/87

params:
  min_dp: 20
  min_alt_ad: 10
  min_alt_vaf: 0.03

vep_db: hg38

design: design.tsv