rule test_gleaves_compatibility:
    input:
        vcf="call.vcf"
    output:
        vcf="annotated.vcf"
    threads: 1
    log:
        "test_gleaves_compatibility.log"
    wrapper:
        "master/bio/BiGR/gleaves_compatibility"