rule bamtools_split:
    input:
        "mapped/{sample}.bam",
    output:
        "mapped/{sample}.REF_xx.bam",
    log:
        "logs/bamtoos_split/{sample}.log",
    params:
        extra="-reference",
    wrapper:
        "master/bio/bamtools/split"
