rule test_variant_occurence_annotate:
    input:
        calls = ["in.vcf", "in2.vcf"],
        occurence = "occurence.txt"
    output:
        calls = ["in.occ.vcf", "in.2.occ.vcf"]
    log:
        "log/variantoccurence/annotate.log"
    wrapper:
        "master/bio/variantoccurence/annotate"
