rule test_eacon_databases:
    output:
        databases = directory("EaCoN_databases"),
        grd = "grd.pl"
    log:
        "EaCoN_databases.log"
    cache: True
    wrapper:
        "master/bio/eacon/databases"
