name: bwa-mem3 index
url: https://github.com/fg-labs/bwa-mem3
description: Index genome sequences with bwa-mem3
author:
  - Thibault Dayris
input:
  - fasta: Path to fasta-formatted genome sequence
output:
  - Path to indexed genome sequence
params:
  - extra: Optional parameters. At publication date, all parameters are automatically inferred.
