rule test_deeptools_plot_correlation:
    input:
        "bins.npz",
    output:
        plot="bins.svg",
        counts="counts.tsv",  # Optional output file
    log:
        "corr.log",
    threads: 1
    params:
        extra="--skipZeros",  # Any optional parameters besides IO and --plotFileFormat
        correlation="spearman",  # either spearman or pearson
        plot="heatmap",  # either heatmap or scatterplot
    wrapper:
        "master/bio/deeptools/plotcorrelation"
