rule deepvariant:
    input:
        bam="mapped/{sample}.bam",
        ref="genome/genome.fasta",
    output:
        vcf="calls/{sample}.vcf.gz",
    log:
        "logs/deepvariant/{sample}/stdout.log",
    threads: 2
    params:
        model="wgs",  # {wgs, wes, pacbio, hybrid}
        sample_name=lambda w: w.sample,  # optional
        extra="",
    wrapper:
        "master/bio/deepvariant"


rule deepvariant_gvcf:
    input:
        bam="mapped/{sample}.bam",
        ref="genome/genome.fasta",
    output:
        vcf="gvcf_calls/{sample}.vcf.gz",
        gvcf="gvcf_calls/{sample}.g.vcf.gz",
    log:
        "logs/deepvariant/{sample}/stdout.log",
    threads: 2
    params:
        model="wgs",  # {wgs, wes, pacbio, hybrid}
        extra="",
    wrapper:
        "master/bio/deepvariant"
