rule test_gseGO:
    input:
        rds = "geneList.RDS"
    output:
        rds = "gseGO.RDS",
        tsv = "gseGO.tsv"
    params:
        gseGO_extra = "pvalueCutoff  = 1, pAdjustMethod = 'BH', by = 'DOSE'"
    wrapper:
        "master/bio/clusterProfiler/gseGO"
