rule test_gseGO:
    input:
        rds = "geneList.RDS"
    output:
        rds = "gseGO.RDS",
        tsv = "gseGO.tsv"
    message:
        "Testing enrichDO"
    threads:
        1
    params:
        gseGO_extra = "pvalueCutoff  = 1, pAdjustMethod = 'BH', by = 'DOSE'"
    log:
        "logs/test_gseGO.log"
    wrapper:
        "master/bio/clusterProfiler/gseGO"
