rule umis_bamtag:
    input:
        "data/{sample}.bam",
    output:
        "data/{sample}.annotated.bam",
    log:
        "logs/umis/bamtag/{sample}.log",
    threads: 1
    params:
        extra="",
    wrapper:
        "master/bio/umis/bamtag"
