rule test_fix_vcf:
    input:
        vcf="in.vcf"
    output:
        vcf="out.vcf"
    log:
        "logs/fix_vcf.log"
    params:
        rename_sample={"fake_KJ660346": 'Sample1'}
    wrapper:
        "master/bio/BiGR/fix_vcf"
