rule SetMateInfo:
    input:
        "mapped/a.bam",
    output:
        "mapped/{sample}.mi.bam",
    log:
        "logs/fgbio/set_mate_info/{sample}.log",
    params:
        "",
    wrapper:
        "master/bio/fgbio/setmateinformation"
