rule test_isoformSwitchAnalyseR_importIsoformExpression:
    input:
        quant = expand(
            "quant/{sample}.chr21.1/quant.sf",
            sample=["a", "b", "c", "d", "e", "f", "g", "h", "i"]
        ),
        design = "design.tsv",
        gtf="annotation.chr21.gtf",
        fasta="genome.chr21.fa"
    output:
        rds = "importIsoformExpression.RDS"
    params:
        extra_isoform_expr = (
            "addIsofomIdAsColumn = TRUE,"
            " ignoreAfterPeriod = TRUE,"
            " ignoreAfterBar = TRUE ,"
            " ignoreAfterSpace = TRUE"
        )
    wrapper:
        "master/bio/isoformSwitchAnalyseR/importIsoformExpression"
