rule tximport:
    input:
        quant = expand("quant/A/quant.sf")
    output:
        txi = "importIsoformExpression.RDS"
    params:
        extra = "addIsofomIdAsColumn = TRUE"
    wrapper:
        "master/bio/isoformSwitchAnalyseR/importIsoformExpression"
