include: "rules/000.commons.smk"
include: "rules/001.bigr.copy.smk"
include: "rules/002.acbs2bed.smk"
include: "rules/003.bedtools.intersect.smk"

rule target:
    input:
        "bedtools/multi_intersect.bed"