rule test_DESeqDataSetFromTximport:
    input:
        tximport = "txi.RDS",
        coldata = "coldata.tsv"
    output:
        dds = "deseq2/dds.RDS"
    message:
        "Testing DESeqDataSetFromTximport"
    log:
        "logs/deseq2/DESeqDataSetFromTximport.logs"
    params:
        design = "~Cond",
        levels = ["A", "B"],
        factor = "Cond"
    wrapper:
        "master/bio/deseq2/DESeqDataSetFromTximport/"
