rule test_rename_snpsift_maf_cols:
    input:
        tsv = "mouse.tsv"
    output:
        tsv = "mouse.renamed.tsv"
    log:
        "logs/renamed.log"
    wrapper:
        "master/bio/BiGR/rename_snpsift_maf_cols"
