name: fd-find
url: https://github.com/sharkdp/fd
description: Find entries in your filesystem
authors:
  - Thibault Dayris
input:
  - Path to directory / directories to search into
output:
  - Path to file(s) list
params:
  - extra: Optional arguments besides positional and `-j | --threads`
  - pattern: Searched pattern
