conda-create-envs-only: true
jobs: 7
local-cores: 7
keep-going: true
rerun-triggers: "mtime"
rerun-incomplete: true
printshellcmds: true
show-failed-logs: true
benchmark-extended: true
software-deployment-method:
  - apptainer
  - conda
