rule test_enrichDGN:
    input:
        rds = "geneList.RDS"
    output:
        rds = "enrichDGN.RDS",
        tsv = "enrichDGN.tsv"
    params:
        enrichDGN_extra = "ont = 'DOLite'"
    wrapper:
        "master/bio/clusterProfiler/enrichDGN"
