rule test_read_peak_file_hg19:
    input:
        bed="peaks.bed.gz"
    output:
        grange="peaks.GRanges.RDS",
        tagmatrix="peaks.TagMatrix.RDS"
    log:
        "logs/readpeaks.log"
    wrapper:
        "master/bio/chipseeker/readPeakFile_hg19"
