rule test_pcaexplorer_pcascree:
    input:
        dst = "vst.RDS"
    output:
        png = "plot.png"
    message:
        "Testing pcaExplorer PCA-Scree"
    threads:
        1
    resources:
        mem_mb = (
            lambda wildcards, attempt: min(attempt * 1024, 10240)
        ),
        time_min = (
            lambda wildcards, attempt: min(attempt * 20, 200)
        )
    params:
        extra = "type = c('pev')"
    log:
        "logs/test_pcaexplorer_pcascree.log"
    wrapper:
        "master/bio/pcaExplorer/PCAScree"
