name: msisensor_table
description: aggregate multiple msi files
author:
  - Thibault Dayris
input:
  - list of msi files
output:
  - a single msi table
params:
  - stability: Threshold used to qualify a tumor (MSS Tumor stable)/(MSI Tumor instable)
