rule strling_merge:
    input:
        bins=["extract/A.bin", "extract/B.bin"],
        reference="reference/genome.fasta",
        fai="reference/genome.fasta.fai",
    output:
        "merged/group-bounds.txt",  # must end with "-bounds.txt"
    log:
        "log/strling/merge/group.log",
    params:
        extra="",  # optionally add further command line arguments
    wrapper:
        "master/bio/strling/merge"
