rule test_maftools_signatures:
    input:
        rds = "tnm.RDS"
    output:
        png = "results/signatures.png",
        rds = "results/signatures.RDS"
    params:
        sig_extra = "n=2"
    wrapper:
        "master/bio/maftools/signatures"
