rule gatk_scatter_interval_by_ns:
    input:
        ref="genome.fasta",
        fai="genome.fasta.fai",
        dict="genome.dict",
    output:
        intervals="genome.intervals",
    log:
        "logs/genome.log",
    resources:
        mem_mb=1024,
    params:
        extra="--MAX_TO_MERGE 10 --OUTPUT_TYPE ACGT",
        java_opts="",  # optional
    wrapper:
        "master/bio/gatk/scatterintervalsbyns"
