rule test_bcfl2fastq:
    input:
        run_dir = directory()
    output:
        out_dir = directory()
        interop_dir = directory()
        stats_dir = directory()
        reports_dir = directory()
    threads: 3
    wrapper:
        "master/bio/bcl2fastq"
