rule test_bcfl2fastq:
    input:
        run_dir = "cellranger-tiny-bcl-1.2.0",
        sample_sheet = "cellranger-tiny-bcl-simple-1.2.0.csv",
        #intensities = "cellranger-tiny-bcl-1.2.0/Data/Intensities"
    output:
        reports_dir = directory("test/output/Reports"),
        stats_dir = directory("test/output/Stats")
    threads: 3
    params:
        extra = (
            " --ignore-missing-controls"
            " --ignore-missing-positions"
            " --ignore-missing-filter"
            " --ignore-missing-bcls"
        ),
        out_dir = "test/output"
    wrapper:
        "master/bio/bcl2fastq"
