rule construct:
    input:
        ref="c.fa",
        vcfgz="c.vcf.gz",
    output:
        vg="graph/c.vg",
    log:
        "logs/vg/construct/c.log",
    threads: 4
    params:
        "--node-max 10",
    wrapper:
        "master/bio/vg/construct"
