rule jellyfish_count:
    input:
        "{prefix}.fasta",
    output:
        "{prefix}.jf",
    log:
        "{prefix}.jf.log",
    threads: 2
    params:
        kmer_length=21,
        size="1G",
        extra="--canonical",
    wrapper:
        "master/bio/jellyfish/count"
