rule baserecalibrator:
    input:
        bam="mapped/{sample}.bam",
        ref="genome.fasta",
        known="dbsnp.vcf.gz"
    output:
        "{sample}.recal_data_table"
    log:
        "logs/gatk3/bqsr/{sample}.log"
    resources:
        mem_mb = 1024
    params:
        extra="",  # optional
    threads: 16
    wrapper:
        "bio/gatk/baserecalibrator"
