rule baserecalibrator:
    input:
        bam="{sample}.bam",
        bai="{sample}.bai",
        ref="genome.fasta",
        fai="genome.fasta.fai",
        dict="genome.dict",
        known="dbsnp.vcf.gz",
        known_idx="dbsnp.vcf.gz.tbi",
    output:
        recal_table="{sample}.recal_data_table",
    log:
        "logs/gatk3/bqsr/{sample}.log",
    threads: 16
    resources:
        mem_mb=1024,
    params:
        extra="--defaultBaseQualities 20 --filter_reads_with_N_cigar",  # optional
    wrapper:
        "master/bio/gatk3/baserecalibrator"
