rule test_paired_dotplots:
    input:
        tsv = ["1.tsv", "2.tsv"]
    output:
        png = "paired_dotplot.png"
    log:
        "seaborn.log"
    wrapper:
        "master/bio/seaborn/paired_dotplots"