rule test_b3sum:
    input:
        "test.rst",
    output:
        "test.b3sum",
    log:
        "test_b3sum.log",
    threads: 1
    params:
        extra="",
    wrapper:
        "master/utils/b3sum"
