rule test_cpat_make_logit_model:
    input:
        coding = "code.fasta",
        noncoding = "nocode.fasta",
        hexamer_table = "hexamer_table"
    output:
        excel = "logit_model.feature.xls",
        rdata = "logit_model.logit.RData",
        rscript = "logit_model.make_logitModel.r"
    wrapper:
        "master/bio/cpat/make_logit_model"
