rule test_cpat_make_logit_model:
    input:
        coding =
        noncoding =
        hexamer_table =
        reference =
    output:
        "logit_model"
    wrapper:
        "master/bio/cpat/make_logit_model"
