set-resources:
  reference_ensembl_annotation_download:
    mem: min(attempt * 400, 1500)
    runtime: min(attempt * 30, 240)
    disk_mb: min(6 * attempt, 30)

    agat_default_config:
      mem: min(attempt * 200, 1000)
      runtime: min(attempt * 5, 10)
      disk_mb: min(5 * attempt, 10)

    go_yq_update_gff_config:
      mem: min(attempt * 400, 900)
      runtime: min(attempt * 5, 10)
      disk_mb: min(attempt * 5, 10)

    go_yq_update_gtf_config:
      mem: min(attempt * 400, 900)
      runtime: min(attempt * 5, 10)
      disk_mb: min(attempt * 5, 10)

    agat_convert_sp_gxf2gxf:
      mem: min(attempt * 9000, 30000)
      runtime: min(attempt * 30, 240)
      disk_mb: min(attempt * 6000, 15000)

    agat_sq_filter_feature_from_fasta:
      mem: min(attempt * 9000, 30000)
      runtime: min(attempt * 30, 240)
      disk_mb: min(attempt * 6000, 15000)

    agat_sp_filter_feature_by_attribute_value:
      mem: min(attempt * 9000, 30000)
      runtime: min(attempt * 30, 240)
      disk_mb: min(attempt * 6000, 15000)

