rule test_enrichNCG:
    input:
        rds = "geneList.RDS"
    output:
        rds = "enrichNCG.RDS",
        tsv = "enrichNCG.tsv"
    params:
        enrichDO_extra = "ont = 'DOLite'"
    wrapper:
        "master/bio/clusterProfiler/enrichNCG"
