rule test_snpsift_vartype:
    input:
        vcf="calls/{sample}.vcf.gz"
    output:
        vcf=temp("snpsift/vartype/{sample}.vcf")
    resources:
        mem_mb==lambda wildcards, attempt: attempt * 1020 + 4096,
        time_min=lambda wildcards, attempt: attempt * 45
    log:
        "logs/snpsift/varType/{sample}.log"
    wrapper:
        "/bio/snpsift/varType"


rule snpeff_annotate:
    input:
        calls="snpsift/vartype/{sample}.vcf",
        db="/mnt/beegfs/database/bioinfo/Index_DB/SnpEff/GRCh38.86/"
    output:
        calls=temp("snpeff/{sample}.vcf"),   # annotated calls (vcf, bcf, or vcf.gz)
        stats="snpeff/{sample}.html",        # summary statistics (in HTML), optional
        csvstats="snpeff/{sample}.csv"       # summary statistics in CSV, optional
    log:
        "logs/snpeff/{sample}.log"
    resources:
        mem_mb==lambda wildcards, attempt: attempt * 1020 + 4096,
        time_min=lambda wildcards, attempt: attempt * 45
    wrapper:
        "/bio/snpeff/annotate"


rule test_snpsift_gmt:
    input:
        call = "snpeff/{sample}.vcf",
        gmt = "/mnt/beegfs/database/bioinfo/Index_DB/MSigDB/GeneSets.gmt"
    output:
        call = temp("snpsift/gmt/{sample}.vcf")
    resources:
        mem_mb==lambda wildcards, attempt: attempt * 1020 + 4096,
        time_min=lambda wildcards, attempt: attempt * 45
    wrapper:
        "/bio/snpsift/genesets"


rule snpsift_clinvar:
    input:
        call="snpsift/gmt/{sample}.vcf",
        database="/mnt/beegfs/database/bioinfo/Index_DB/ClinVar/GRCh38/clinvar_20210102.vcf.gz"
    output:
        call=tmp("snpsift/clinvar/{sample}.vcf")
    log:
        "logs/snpsift/clinvar/{sample}.log"
    resources:
        mem_mb==lambda wildcards, attempt: attempt * 1020 + 4096,
        time_min=lambda wildcards, attempt: attempt * 45
    wrapper:
        "/bio/snpsift/annotate"


rule snpsift_kaviar:
    input:
        call="snpsift/clinvar/{sample}.vcf",
        database="/mnt/beegfs/database/bioinfo/Index_DB/Kaviar/HG38/Kaviar-160204-Public/vcfs/Kaviar-160204-Public-hg38-trim.vcf.gz"
    output:
        call=temp("snpeff/kaviar/{sample}.vcf")
    log:
        "logs/snpsift/kaviar/{sample}.log"
    resources:
        mem_mb==lambda wildcards, attempt: attempt * 1020 + 4096,
        time_min=lambda wildcards, attempt: attempt * 45
    wrapper:
        "/bio/snpsift/annotate"


rule snpsift_dbsnp:
    input:
        call="snpeff/kaviar/{sample}.vcf",
        database="/mnt/beegfs/database/bioinfo/Index_DB/dbSNP/GRCh38p7/All_20180418.vcf.gz"
    output:
        call=temp("snpeff/dbsnp/{sample}.vcf")
    log:
        "logs/snpsift/dbsnp/{sample}.log"
    resources:
        mem_mb==lambda wildcards, attempt: attempt * 1020 + 4096,
        time_min=lambda wildcards, attempt: attempt * 45
    wrapper:
        "/bio/snpsift/annotate"


rule snpsift_exac:
    input:
        call="snpeff/dbsnp/{sample}.vcf",
        database="/mnt/beegfs/database/bioinfo/Index_DB/Exac/release1/ExAC.r1.sites.vep.vcf.gz"
    output:
        call=temp("snpeff/exac/{sample}.vcf")
    log:
        "logs/snpsift/exac/{sample}.log"
    resources:
        mem_mb==lambda wildcards, attempt: attempt * 1020 + 4096,
        time_min=lambda wildcards, attempt: attempt * 45
    wrapper:
        "/bio/snpsift/annotate"


rule snpsift_gwascat:
    input:
        call = "snpeff/exac/{sample}.vcf",
        gwascat = "/mnt/beegfs/database/bioinfo/Index_DB/GWASCatalog/gwas_catalog_v1.0.2-studies_r2020-05-03.tsv"
    output:
        call = temp("snpeff/gwascat/{sample}.vcf")
    resources:
        mem_mb==lambda wildcards, attempt: attempt * 1020 + 4096,
        time_min=lambda wildcards, attempt: attempt * 45
    wrapper:
        "/bio/snpsift/gwascat"
