rule lastdb_transcript:
    input:
        "test-transcript.fa",
    output:
        "test-transcript.fa.prj",
    log:
        "logs/lastdb/test-transcript.log",
    params:
        protein_input=False,
        extra="",
    wrapper:
        "master/bio/last/lastdb"


rule lastdb_protein:
    input:
        "test-protein.fa",
    output:
        "test-protein.fa.prj",
    log:
        "logs/lastdb/test-protein.log",
    params:
        protein_input=True,
        extra="",
    wrapper:
        "master/bio/last/lastdb"
