# General pipeline options
max_threads: 20


# Select which parts of the pipeline should be run
steps:
  qc: true
  quant: false
  dge: false
  fusions: false
  immunedeconv: false
  gsea: false
  variants: false


# Path to design file (relative or absolute)
design: design.tsv


# A short list of genes of interest
# Dedicated plots will be performed on these genes
genes_of_interest:
  - ENSMUSG00000034218


# Fastp parameters
fastp:
  adapters: none
  fastp_extra: --cut_front --cut_tail --cut_window_size 6 --cut_mean_quality 10 --unqualified_percent_limit 50 --n_base_limit 7 --average_qual 0 --length_required 15 --overrepresentation_analysis


# Salmon parameters
salmon:
  index: /mnt/beegfs/database/bioinfo/Index_DB/Salmon/mm10/index
  salmon_libtype: A
  salmon_quant_extra: --numBootstraps 100 --gcBias --seqBias --posBias


# DESeq2 parameters
deseq2:
  design:
    columns_to_aggregate: null
    columns_to_ignore: null
    include_only: null
  tximport_extra: type='salmon', ignoreTxVersion=TRUE, ignoreAfterBar=TRUE
  thresholds:
    alpha: 0.05
    fc: 0.6


# Multiqc parameters
multiqc:
  title: Differential Gene Expression
  report_comment: This report has been made at Gustave Roussy
  email: bigr@gustaveroussy.fr
  application_type: RNA-Seq
  project_type: Application


# Rust-Bio-Tools
rbt:
  csv_extra: '--separator "\\t" --sort-column stat_change --sort-order ascending --rows-per-page 50'
  zip_extra: --create --bzip2


# Star patameters
star:
  index: /mnt/beegfs/database/bioinfo/Index_DB/STAR/GRCm38
  chimera_extra: --outReadsUnmapped None --twopassMode Basic --outSAMstrandField intronMotif --outSAMunmapped Within --chimSegmentMin 12 --chimJunctionOverhangMin 8 --chimOutJunctionFormat 1 --alignSJDBoverhangMin 10 --alignMatesGapMax 100000 --alignIntronMax 100000 --alignSJstitchMismatchNmax 5 -1 5 5 --outSAMattributes Standard --chimMultimapScoreRange 3 --chimScoreJunctionNonGTAG -4 --chimMultimapNmax 20 --chimNonchimScoreDropMin 10 --peOverlapNbasesMin 12 --peOverlapMMp 0.1 --alignInsertionFlush Right --alignSplicedMateMapLminOverLmate 0 --alignSplicedMateMapLmin 30
  variant_extra: --outFilterType BySJout --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverReadLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outSAMattributes Standard --twopassMode Basic


# Quality controls
rseqc:
  tin: --sample-size 100 --minCov 10
  bam_stat: --mapq 30
  gene_body: --format pdf
  junction_annotation: --mapq 30 

# Samtools extra parameters
# Be careful with parameters, do not break compatibility
samtools:
  index_extra: ""
  cram_extra: ""
  stats: ""


# Star-fusion parameters and database
star_fusion:
  CTAT_resource_lib: /mnt/beegfs/database/bioinfo/Index_DB/CTAT_Resource_Lib/GRCh38_gencode_v37/GRCh38_gencode_v37_CTAT_lib_Mar012021.plug-n-play/ctat_genome_lib_build_dir/
  extra: --FusionInspector inspect



# Arriba fusion detection
arriba:
  extra: ""



# Sambamba optional parameters
sambamba:
  sort: ""


# GATK parameters
gatk:
  baserecalibrator: ""
  applybqsr: ""
  mutect2_extra: --max-reads-per-alignment-start 0 --disable-read-filter MateOnSameContigOrNoMappedMateReadFilter
  pileup_summaries: ""
  calculate_contamination: ""
  learn_read_orientation_model: ""
  splitncigarreads_extra: "--create-output-bam-index"


# Fastq screen parameters
# Add new genomes below
fastq_screen:
  fastq_screen_config:
    database:
      Contaminants:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Adapters/Contaminants
      AThaliana:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Arabidopsis/Arabidopsis_thaliana.TAIR10
      Drosophila:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Drosophila/BDGP6
      Ecoli:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/E_coli/Ecoli
      Human:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Human/Homo_sapiens.GRCh38
      Lambda:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Lambda/Lambda
      Mitochondria:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Mitochondria/mitochondria
      Mouse:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Mouse/Mus_musculus.GRCm38
      PhiX:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/PhiX/phi_plus_SNPs
      Rat:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Rat/Rnor_6.0
      rRNA:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/rRNA/GRCm38_rRNA
      Vectors:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Vectors/Vectors
      Worm:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Worm/Caenorhabditis_elegans.WBcel235
      Yeast:
        bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Yeast/Saccharomyces_cerevisiae.R64-1-1
    aligner_paths:
      bowtie2: bowtie2
  subset: 100000
  aligner: bowtie2


# Immunedeconv parameters
# Add new tools below
immunedeconv:
  cibersort_binary: "/mnt/beegfs/software/cibersort/1.0.6/CIBERSORT.R"
  cibersort_mat: "/mnt/beegfs/software/cibersort/1.0.6/LM22.txt"
  tool_list: 
    - xcell
    - quantiseq
    - epic
    - mcp_counter
    - cibersort
    - cibersort_abs


# ClusterProfiler
clusterprofiler:
  organism: Mm
  rank_on: padj
  enrich_gmt: "pvalueCutoff = 1, qvalueCutoff = 1"
  enrich_do: "pvalueCutoff = 1, qvalueCutoff = 1"
  enrich_dgn: "pvalueCutoff = 1, qvalueCutoff = 1"
  enrich_ncg: "pvalueCutoff = 1, qvalueCutoff = 1"
  barplot_extra: "color = 'p.adjust', showCategory = 8"
  dotplot_extra: "showCategory = 10"
  heatplot_extra: "showCategory = 10"
  upsetplot_extra: "n = 8"
  gmt:
    MSigDB_M1_Positional_Gene_Sets: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/m1.all.v2023.1.Mm.entrez.gmt
    MSigDB_M2_Curated_Gene_Sets: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/m2.all.v2023.1.Mm.entrez.gmt
    MSigDB_M2_Chemical_Genetic_Perturbations: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/m2.cgp.v2023.1.Mm.entrez.gmt
    Biocarta_Canonical_Pathway: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/m2.cp.biocarta.v2023.1.Mm.entrez.gmt
    Reactome_Canonical_Pathway: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/m2.cp.reactome.v2023.1.Mm.entrez.gmt
    MSigDB_M2_Canonical_Pathways: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/m2.cp.v2023.1.Mm.entrez.gmt
    Wikipathway_Canonical_Pathways: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/m2.cp.wikipathways.v2023.1.Mm.entrez.gmt
    MSigDB_M3_Regulatory_Target_Gene_Sets: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/m3.all.v2023.1.Mm.entrez.gmt
    Kolmykov_Transcription_Factor: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/m3.gtrd.v2023.1.Mm.entrez.gmt
    miRDB: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/m3.mirdb.v2023.1.Mm.entrez.gmt
    MSigDB_M5_Ontology_Gene_Set: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/m5.all.v2023.1.Mm.entrez.gmt
    Gene_Othology_BP: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/m5.go.bp.v2023.1.Mm.entrez.gmt
    Gene_Othology_CC: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/m5.go.cc.v2023.1.Mm.entrez.gmt
    Gene_Othology_MF: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/m5.go.mf.v2023.1.Mm.entrez.gmt
    Gene_Othology_All: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/m5.go.v2023.1.Mm.entrez.gmt
    Mamalian_Phenotype_Ontology: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/m5.mpt.v2023.1.Mm.entrez.gmt
    MSigDB_M8_Cell_Type_Signatures: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/m8.all.v2023.1.Mm.entrez.gmt
    MSigDB_M0_Hallmark_Gene_Sets: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/mh.all.v2023.1.Mm.entrez.gmt
    MSigDB_All: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/mouse/msigdb.v2023.1.Mm.entrez.gmt
  ppi:
    STRING: /mnt/beegfs/database/bioinfo/Index_DB/PPI_Hotspot/mouse/10090.protein.enrichment.terms.v11.5.txt
    

# Genome information
# If you change genome data, please re-build all indexes.
reference:
  genome_name: GRCm38.99
  gtf: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCm38.99/GRCm38.99.mus_musculus.gtf
  genome: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCm38.99/GRCm38.99.mus_musculus.dna.fasta
  genome_dict: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCm38.99/GRCm38.99.mus_musculus.dna.dict
  genome_index: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCm38.99/GRCm38.99.mus_musculus.dna.fasta.fai
  refflat: /mnt/beegfs/database/bioinfo/Index_DB/refFlat/GRCm38/refFlat.txt.gz
  refgene_model: /mnt/beegfs/database/bioinfo/Index_DB/refgene/bed12/GRCm38/GRCm38.nochr.bed12
  capture_kit_bed: /mnt/beegfs/database/bioinfo/Index_DB/captureKitDesigns/hg38/v5/sureselect_v5.padded.nochr.bed
  af_only: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCm38.99/GRCm38.99.mus_musculus.all.vcf.gz
  af_only_tbi: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCm38.99/GRCm38.99.mus_musculus.all.vcf.gz.tbi
  dbsnp: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCm38.99/GRCm38.99.mus_musculus.all.vcf.gz
  dbsnp_tbi: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCm38.99/GRCm38.99.mus_musculus.all.vcf.gz.tbi
  capturekit_bed: /mnt/beegfs/database/bioinfo/Index_DB/captureKitDesigns/mm10/v1/mm9_sureselect_v1.padded.bed
  chromosomes:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
    - "13"
    - "14"
    - "15"
    - "16"
    - "17"
    - "18"
    - "19"
    - "20"
    - "21"
    - "22"
    - X
    - Y
    - MT