rule test_gseNCG:
    input:
        rds = "geneList.RDS"
    output:
        rds = "gseNCG.RDS",
        tsv = "gseNCG.tsv"
    params:
        gseNCG_extra = "pvalueCutoff  = 1, pAdjustMethod = 'BH', by = 'DOSE'"
    wrapper:
        "master/bio/clusterProfiler/gseNCG"
