rule test_gseNCG:
    input:
        rds = "geneList.RDS"
    output:
        rds = "gseNCG.RDS",
        tsv = "gseNCG.tsv"
    message:
        "Testing enrichDO"
    threads:
        1
    params:
        gseNCG_extra = "pvalueCutoff  = 1, pAdjustMethod = 'BH', by = 'DOSE'"
    log:
        "logs/test_gseNCG.log"
    wrapper:
        "master/bio/clusterProfiler/gseNCG"
