rule diamond_blastx:
    input:
        fname_fastq="{sample}.fastq",
        fname_db="db.dmnd",
    output:
        fname="{sample}.tsv.gz",
    log:
        "logs/diamond_blastx/{sample}.log",
    threads: 8
    params:
        extra="--header --compress 1",
    wrapper:
        "master/bio/diamond/blastx"
