rule preseq_lc_extrap_bam:
    input:
        "samples/{sample}.sorted.bam",
    output:
        "test_bam/{sample}.lc_extrap",
    log:
        "logs/test_bam/{sample}.log",
    params:
        "-v",  #optional parameters
    wrapper:
        "master/bio/preseq/lc_extrap"


rule preseq_lc_extrap_bed:
    input:
        "samples/{sample}.sorted.bed",
    output:
        "test_bed/{sample}.lc_extrap",
    log:
        "logs/test_bed/{sample}.log",
    params:
        "-v",  #optional parameters
    wrapper:
        "master/bio/preseq/lc_extrap"
