rule test_split_multiallelic:
    input:
        vcf="in.vcf"
    output:
        vcf="out.vcf"
    log:
        "logs/split_vcf_multiallelic.log"
    wrapper:
        "master/bio/BiGR/split_vcf_multiallelic"
