rule test_irods_extract_metadata:
    input:
        "metadata.yaml"
    output:
        "extraction.tsv"
    params:
        attributes = ["SampleID", "Condition", "Strand"]
    wrapper:
        "master/bio/iRODS/extract_metadata"
