rule test_dysk:
    input:
        # Optional path to a mounting point to analyse
        ".",
    output:
        "dysk.txt",
    threads: 1
    log:
        "test_dysk.log",
    params:
        extra="",
    wrapper:
        "master/utils/dysk"


rule test_dysk_json:
    output:
        "dysk.json",
    threads: 1
    log:
        "test_dysk_json.log",
    params:
        extra="",
    wrapper:
        "master/utils/dysk"


rule test_dysk_csv:
    output:
        "dysk.csv",
    threads: 1
    log:
        "test_dysk_csv.log",
    params:
        extra="",
    wrapper:
        "master/utils/dysk"


rule test_dysk_tsv:
    output:
        "dysk.tsv",
    threads: 1
    log:
        "test_dysk_tsv.log",
    params:
        extra="",
    wrapper:
        "master/utils/dysk"
