rule test_tximeta:
    input:
        coldata="coldata.tsv",
    output:
        txi="txi.RDS",
    threads: 1
    log:
        "logs/tximeta.log"
    params:
        extra_tximeta=""
    wrapper:
        "master/bio/tximeta/tximeta"