rule salmon_index:
    input:
        sequences = "gentrome.fasta",
        decoys = "decoys.txt"
    output:
        index = directory("salmon/transcriptome_index")
    log:
        "logs/salmon/transcriptome_index.log"
    threads: 2
    params:
        # optional parameters
        extra="-k 11"
    wrapper:
        "master/bio/salmon/index"
