from snakemake.utils import min_version
from typing import Any

min_version("6.0")

default_moose_config = {
    # Path to interop_dir, the initial input directory given by sequencer
    "interop_dir": "."
    # Path to run directory, the final output directory where fastq files
    # are expected to be.
    "run_dir": ".",
    # Path to sample_sheet
    "sample_sheet": "sample_sheet.csv",
    # Path to the default configfile
    "config": "/home/svc_moose@intra.igr.fr/repo_git/MoOSe/moose_pipeline/config.yaml",
    # Flowcell size (small = 1, medium = 2, big = 3, very big = 4)
    # Each increase of this value will add 12 extra hours to both
    # bcl2fastq and rsync step
    "flowcell_size": 1,
    # Wether we are working with dual indexing, there are additional output
    # files which have to be listed for better tracking.
    "dual": False,
    # Wether we are working with UMI, there are additional output
    # files which have to be listed for better tracking.
    "umi": False
}

try:
    if config == dict():
        config = default_moose_config
except NameError:
    config = default_moose_config

def list_undetermined(dual: bool = False, umi: bool = False) -> list[str]:
    """
    Based on the possible sequencing mode,
    return the expected undetermined files
    """
    yield from ["R1", "R2", "I1"]

    if dual is True:
        yield "I2"

    if umi is True:
        yield "R3"


def fastq_replace_suffix(fastq_path: str, new_suffix: str = "") -> str:
    for suffix in [".fastq", ".fq", ".fastq.gz", ".fq.gz"]:
        if fastq_path.endswith(suffix):
            return fastq_path.replace(suffix, new_suffix)
    raise ValueError(f"Could not guess fastq suffix for {fastq_path}")


def get_prefix(fastq_list: list[str]) -> list[str]:
    yield from [fastq_file_prefix(fq) for fq in fastq_list]


def get_md5(fastq_list: list[str]) -> list[str]:
    yield from [fastq_file_prefix(fq, ".fastq.gz.md5") for fq in fastq_list]


def get_fastqc_html(fastq_list: list[str]) -> list[str]:
    yield from [fastq_file_prefix(fq, "_fastqc.html") for fq in fastq_list]


def get_fastqc_zip(fastq_list: list[str]) -> list[str]:
    yield from [fastq_file_prefix(fq, "_fastqc.zip") for fq in fastq_list]


workdir: config["run_dir"]
configfile: config["config"]


onstart:
    touch("pipeline.running")
    print("Starting the demux pipeline")

onsuccess:
    touch("pipeline.successful")
    print("Pipeline is over and successful")

onerror:
    touch("pipeline.failed")
    print("Pipeline returned non-zero status")


rule all:
    input:
        qc="multiqc.html",
        fastq=expand(
            "fastqc/{sample}.fastq.gz",
            sample=design["Sample_id"]
        )


module fastqc_multiqc:
    snakefile: "../fastqc_multiqc/Snakefile"
    config: dict()


use rule * from fastqc_multiqc as *


use rule rule multiqc form fastqc_multiqc with:
    input:
        fqc_zip=expand(
            "fastqc/{sample}_fastqc.zip",
            sample=design["Sample_id"]
        ),
        fqc_html=expand(
            "fastqc/{sample}_fastqc.html",
            sample=design["Sample_id"]
        ),
        txt=expand(
            "fastq_screen/{sample}.fastq_screen.txt",
            sample=design["Sample_id"]
        ),
        png=expand(
            "fastq_screen/{sample}.fastq_screen.png",
            sample=design["Sample_id"]
        ),
        bcl_stats="unaligned/Stats/"


"""
Previously moose used to copy files before bcl2fastq. This copy is kept
separately.
"""
rule rsync_interop:
    input:
        config["interop_dir"]
    output:
        directory("InterOp")
    message:
        "Copying InterOp dir from {input} to {output}"
    threads: 1
    resources:
        mem_mb=lambda wildcards, attempt: attempt * 1024,
        time_min=lambda wildcards, attempt: attempt * 60 * 2 * config.get("flowcell_size", 1)
    params:
        "--verbose "  # Increase verbosity
        "--checksum "  # Checksum
        "--recursive "  # Recursive copy
        "--update "  # Do not copy files that already exists
        "--links "  # Symlinks stay as symlinks
        "--perms "  # Preserve permissions
        "--times "  # Perserve modification times
        "--human-readable"  # Number in humand readable formats
    log:
        "logs/rsync/interop.log"
    shell:
        "rsync {params} {input} {output} > {log} 2>&1"


"""
Actual demultiplexing step
"""
rule bcl2fastq:
    input:
        run_dir=config["run_dir"],
        sample_sheet=config["sample_sheet"],
        interop_dir=directory("InterOp")
    output:
        reports_dir=directory("unaligned/Reports/"),
        stats_json=directory("unaligned/Stats/")
        undetermined=expand(
            "unaligned/Undetermined_S0_{undetermined}_001.fastq.gz,
            undetermined=list_undetermined(config["dual"], config["umi"])
        )
    message:
        "Running bcl2fastq on {config['run_dir']}"
    threads: config.get("threads", 36)
    resources:
        mem_mb=lambda wildcards, attempt: min(attempt * 10240 + 20480, 51200),
        time_min=lambda wildcards, attempt: attempt * 60 * 12 * config.get("flowcell_size", 1)
    log:
        "logs/bcl2fastq/demux.log"
    params:
        extra=(
            "--fastq-compression-level 6 "
            "--mask-short-adapter-reads 1 "
            "--create-fastq-for-index-reads "
        ),
        out_dir=config["out_dir"],
        use_bases_mask=config.get("use_bases_mask", None)
        no_lane_splitting=config.get("no_lane_splitting", False),
        barcode_mismatches=config.get("barcode_mismatches", None)
    wrapper:
        "/bio/bcl2fastq"
