rule samtools_index:
    input:
        "mapped/{sample}.sorted.bam",
    output:
        "mapped/{sample}.sorted.bam.bai",
    log:
        "logs/samtools_index/{sample}.log",
    threads: 4  # This value - 1 will be sent to -@
    params:
        extra="",  # optional params string
    wrapper:
        "master/bio/samtools/index"
