rule test_enrich_heatplot:
    input:
        genelist = "geneList.RDS"
    output:
        png = "pathview.png"
    params:
        pathway_id = "hsa04110"
    wrapper:
        "master/bio/clusterProfiler/pathview"
