rule diamond_makedb:
    input:
        fname="{reference}.fasta",
    output:
        fname="{reference}.dmnd",
    log:
        "logs/diamond_makedb/{reference}.log",
    threads: 8
    params:
        extra="",
    wrapper:
        "master/bio/diamond/makedb"
