rule samtools_view:
    input:
        "{sample}.sam",
    output:
        bam="{sample}.bam",
        idx="{sample}.bai",
    log:
        "{sample}.log",
    threads: 2
    params:
        extra="",  # optional params string
        region="",  # optional region string
    wrapper:
        "master/bio/samtools/view"
