name: sha256sum
url: https://manpages.ubuntu.com/manpages/questing/man1/sha256sum.1.html
description:
  Compute and check sha256sums
authors:
  - Thibault Dayris
input:
  - Path(s) to file(s) to compute sha256sum onto
output:
  - Path to sha256sums or check results
params:
  - extra: Optional arguments besides IO
