from snakemake.utils import min_version

min_version("9.13.1")


configfile: "config.yaml"


module star_arriba:
    config:
        config
    meta_wrapper:
        "file:.."


use rule * from star_arriba
