rule sambamba_index:
    input:
        "mapped/{sample}.bam",
    output:
        "mapped/{sample}.bam.bai",
    log:
        "logs/sambamba-index/{sample}.log",
    threads: 8
    params:
        extra="",  # optional parameters
    wrapper:
        "master/bio/sambamba/index"
