rule test_cancer_census_annotate:
    input:
        vcf="in.vcf",
        cgc="db.csv"
    output:
        vcf="out.vcf"
    log:
        "cancer_census.log"
    wrapper:
        "master/bio/BiGR/cancer_gene_census_annotate"
