rule star_index:
    input:
        fasta="{genome}.fasta",
    output:
        directory("{genome}"),
    log:
        "logs/star_index_{genome}.log",
    threads: 1
    params:
        extra="",
    message:
        "Testing STAR index"
    wrapper:
        "master/bio/star/index"
