rule homer_makeTagDir:
    input:
        # input bam, can be one or a list of files
        bam="{sample}.bam",
    output:
        directory("tagDir/{sample}"),
    log:
        "logs/makeTagDir/{sample}.log",
    params:
        extra="",  # optional params, see homer manual
    wrapper:
        "master/bio/homer/makeTagDirectory"
