include: "rules/000.common.smk"
include: "rules/001.picard.samtofq.smk"
include: "rules/002.cutadapt.smk"
include: "rules/003.bwa.mem.smk"
include: "rules/004.sambamba.smk"
include: "rules/005.gatk.germline.smk"
include: "rules/006.grep.smk"
include: "rules/007.gatk.baseline.smk"
include: "rules/008.grep.baseline.smk"
include: "rules/009.gatk.somatic.smk"
include: "rules/010.filter.vcf.smk"
include: "rules/011.bam_readcount.smk"
include: "rules/012.bcr2vep.smk"
include: "rules/013.mutect.vep.smk"
include: "rules/014.bigtable.smk"
include: "rules/015.brc.vep.smk"
include: "rules/016.hc.vep.smk"
include: "rules/017.bigr_copy.smk"
include: "rules/018.gatk.wbc.smk"
include: "rules/019.vep.baseline.wbc.smk"


rule target:
    input:
        raw=expand("gatk/mutect2/{sample}.vcf.gz", sample=samples_list),
        raw_indexes=expand("gatk/mutect2/{sample}.vcf.gz.tbi", sample=samples_list),
        annotated="data_output/bigtable.tsv",
