include: "rules/000.common.smk"
include: "rules/001.picard.samtofq.smk"
include: "rules/002.cutadapt.smk"
include: "rules/003.bwa.mem.smk"
include: "rules/004.sambamba.smk"
include: "rules/005.gatk.germline.smk"
include: "rules/006.grep.smk"
include: "rules/007.gatk.baseline.smk"
include: "rules/008.grep.baseline.smk"
include: "rules/009.gatk.somatic.smk"
include: "rules/010.bam_readcount.smk"
include: "rules/011.bcr2vep.smk"
include: "rules/013.bigr_copy.smk"


rule target:
    input:
        raw=expand("gatk/mutect2/{sample}.vcf.gz", sample=samples_list),
        annotated=expand("vep/bcr/{sample}.vcf", sample=samples_list),
