---
name: BCFTools annotate
description: Annotate VCF/BCF with BCFtools
authors:
  - Thibault Dayris
input:
  - mane: Path to MANE database
  - revel: Path to Revel database
  - mistic: Path to Mistic datavase
output:
  - Annotated VCF
