rule test_multiqc_dir:
    input:
        expand("samtools_stats/{sample}.txt", sample=["a", "b"]),
    output:
        "qc/multiqc.html",
        directory("qc_data/multiqc_data"),
    log:
        "logs/multiqc.log",
    params:
        extra="--verbose",  # Optional: extra parameters for multiqc.
    wrapper:
        "master/bio/multiqc"


rule test_multiqc_file:
    input:
        expand("samtools_stats/{sample}.txt", sample=["a"]),
    output:
        "qc/multiqc.a.html",
        "qc_data/multiqc.a_data.zip",
    log:
        "logs/multiqc.log",
    params:
        extra="--verbose",  # Optional: extra parameters for multiqc.
        use_input_files_only=True,  # Optional, use only a.txt and don't search folder samtools_stats for files
    wrapper:
        "master/bio/multiqc"


rule test_multiqc_config:
    input:
        expand("samtools_stats/{sample}.txt", sample=["a", "b"]),
        config="config/multiqc_config.yaml",
    output:
        "qc/multiqc.config.html",
        "qc_data/multiqc.config_data.zip",
    log:
        "logs/multiqc.log",
    params:
        extra="--verbose",
    wrapper:
        "master/bio/multiqc"
