from snakemake.utils import min_version

min_version("9.13.1")


configfile: "config.yaml"


module bwa_mapping:
    config:
        config
    meta_wrapper:
        "file:.."


use rule * from bwa_mapping
