rule test_ngsbits_sampleancestry:
    input:
        # Either a single VCF or a list of VCF files
        "sample.vcf",
    output:
        "ancestry.tsv",
    log:
        "ancestry.log",
    threads: 1
    params:
        extra="-min_snps 4 -build hg19",
    wrapper:
        "master/bio/ngsbits/sampleancestry"
