rule test_cibersort_abs:
    input:
        quant="quantification.tsv",
        cibersort_binary="/path/to/cibersort/non/free",
        cibersort_mat="/path/to/celltypes.mat"
    output:
        histogram="celltypes.hist.png",
        dotplot="celltypes.dotplot.png",
        plotdir=directory("celltypes.dotplots"),
        tsv="celltypes.tsv",
        rds="celltypes.RDS"
    params:
        method="cibersort",
        gene_col="GENE",
        extra="tumor = TRUE, column = 'gene_symbol'",
    wrapper:
        "master/bio/immunedeconv/deconvolute"
