rule test_groupGO:
    input:
        rds = "geneList.RDS"
    output:
        rds = "groupGO.RDS",
        tsv = "groupGO.tsv"
    message:
        "Testing enrichDO"
    log:
        "logs/test_groupGO.log"
    wrapper:
        "master/bio/clusterProfiler/groupGO"
