rule sambamba_flagstat:
    input:
        "mapped/{sample}.bam",
    output:
        "mapped/{sample}.stats.txt",
    log:
        "logs/sambamba-flagstat/{sample}.log",
    threads: 1
    params:
        extra="",  # optional parameters
    wrapper:
        "master/bio/sambamba/flagstat"
