name: fq lint
url: https://github.com/stjude-rust-labs/fq
description: Validates a FASTQ file pair
authors:
  - Thibault Dayris
input:
  - Path(s) to fastq file(s)
output:
  - Path to validation result
params:
  - extra: Optional parameters
notes: |
  Find the list of validators here: https://github.com/stjude-rust-labs/fq#validators
