rule test_tximeta_makelinkedtxome:
    input:
        index="dummy_index",
        fasta="dummy_tx.fasta",
        gtf="dummy.gtf",
    output:
        "dummy.json",
    params:
        source="Local",
        organism="dummy",
        release=2022,
        genome="dummy-2022",
    log:
        "tximeta.log",
    wrapper:
        "master/bio/tximeta/makelinkedtxome"
