rule tximeta_make_linked_txome_from_directory:
    input:
        salmon_index="transcriptome_index",
        fasta="transcripts.fasta",
        gtf="annotation.gtf",
    output:
        json="linkedtxome.json"
    threads: 1
    log:
        "logs/tximeta.log"
    params:
        organism="Dummy", # Required, name of the organism
        release=1, # Required, release number/code
        genome="GRCdummy1", # Required, genome code
        source="imagination", # Required, source of the annotations
    wrapper:
        "master/bio/tximeta"