name: rst2html
url: https://docutils.sourceforge.io/docs/user/tools.html#rst2html
description: |
  rst2html is the front-end for the default Docutils HTML writer. The default writer 
  may change with the development of HTML, browsers, Docutils, and the web.
authors:
  - Thibault Dayris
input:
  - rst: Path to RST input file
  - config: Optional path to configuration file
  - url_template: Optional path to file-to-file url template
  - rfc_url: Optional path to base URL for RFC references
  - html_template: Optional path to base template file
  - stylesheet: Optional path to CSS stylesheet paths
output:
  - html: Path to html output path
  - warnings: Optional path to processing warnings
  - dependencies: Optional path to file dependencies
