rule test_maf2bed:
    input:
        maf="variants.maf",
    output:
        bed3="variants.3.bed",
        bed4="variants.4.bed",
        bed6="variants.6.bed",
        bed9="variants.9.bed",
    threads: 1
    log:
        "logs/maf2bed.log"
    wrapper:
        "master/BiGR/maf2bed"