rule denoisereadcounts:
    input:
        hdf5=["a.counts.hdf5"],
    output:
        std_copy_ratio="a.standardizedCR.tsv",
        denoised_copy_ratio="a.denoisedCR.tsv",
    log:
        "logs/gatk/denoisereadcounts.log",
    resources:
        mem_mb=1024,
    params:
        extra="",  # optional
        java_opts="",  # optional
    wrapper:
        "master/bio/gatk/denoisereadcounts"
