rule apply_vqsr:
    input:
        vcf="test.vcf",
        recal="snps.recal",
        tranches="snps.tranches",
        ref="ref.fasta",
    output:
        vcf="test.snp_recal.vcf",
    log:
        "logs/gatk/applyvqsr.log",
    resources:
        mem_mb=1024,
    params:
        mode="SNP",  # set mode, must be either SNP, INDEL or BOTH
        extra="",  # optional
    wrapper:
        "master/bio/gatk/applyvqsr"
