---
name: pcaExplorer limmago
description: Run quick limma go-term analysis
authors:
  - Thibault Dayris
input:
  - A dds object of all samples and targets
  - A normalized dds (vst/rlog) of all samples and targets
output:
  - A RDS file contianing the result of go-terms enrichment
notes: |
  This is only used by pcaExplorer and has no other purpose.
  This is not a differential analysis result.
  This is not a differential-expression-based go-term enrichment.

  Supported organisms:

  * hs: Homo Sapiens
  * mm: Muus Musculus
