rule get_genome:
    output:
        "refs/genome.fasta",
    log:
        "logs/get_genome.log",
    cache: "omit-software"  # save space and time with between workflow caching (see docs)
    params:
        species="saccharomyces_cerevisiae",
        datatype="dna",
        build="R64-1-1",
        release="98",
    wrapper:
        "master/bio/reference/ensembl-sequence"


rule get_genome_gzipped:
    output:
        "refs/genome.fa.gz",
    log:
        "logs/get_genome.log",
    cache: "omit-software"  # save space and time with between workflow caching (see docs)
    params:
        species="saccharomyces_cerevisiae",
        datatype="dna",
        build="R64-1-1",
        release="98",
    wrapper:
        "master/bio/reference/ensembl-sequence"


rule get_single_chromosome:
    output:
        "refs/chr2.fasta",
    log:
        "logs/get_genome.log",
    cache: "omit-software"  # save space and time with between workflow caching (see docs)
    params:
        url="http://ftp.ensembl.org/pub",
    wrapper:
        "master/bio/reference/ensembl-sequence"


rule get_multiple_chromosome:
    output:
        "refs/chr6_and_chr1.fasta",
    log:
        "logs/get_genome.log",
    cache: "omit-software"  # save space and time with between workflow caching (see docs)
    params:
        species="saccharomyces_cerevisiae",
        datatype="dna",
        build="R64-1-1",
        release="113",
        chromosome=["VI", "I"],  # optional: restrict to one or multiple chromosomes
        # branch="plants",  # optional: specify branch
    wrapper:
        "master/bio/reference/ensembl-sequence"


rule get_multiple_chromosomes_gzipped:
    output:
        "refs/chr6_and_chr1.fa.gz",
    log:
        "logs/get_genome.log",
    cache: "omit-software"  # save space and time with between workflow caching (see docs)
    params:
        species="saccharomyces_cerevisiae",
        datatype="dna",
        build="R64-1-1",
        release="113",
        chromosome=["VI", "I"],  # optional: restrict to one or multiple chromosomes
        # branch="plants",  # optional: specify branch
    wrapper:
        "master/bio/reference/ensembl-sequence"
