rule test_irods_search_samples:
    input:
        samples="sample.list"
    output:
        "design.tsv"
    params:
        samples=["MR495-T1"]
    wrapper:
        "master/bio/iRODS/search_samples"
