rule test_isoformSwitchAnalyseR_dexseq:
    input:
        switch_list = "switch_list.RDS"
    output:
        rds = "tested.RDS"
    wrapper:
        "master/bio/isoformSwitchAnalyzeR/isoformSwitchTestDEXSeq"
