rule test_ensembl_remove_patch_cdna:
    input:
        fasta = "test.fasta"
    output:
        fasta = "corrected.fasta"
    message:
        "Testing the ensembl patch removal on CDNA fasta files"
    threads:
        1
    resources:
        mem_mb = (
            lambda wildcards, attempt: min(attempt * 1024, 10240)
        ),
        time_min = (
            lambda wildcards, attempt: min(attempt * 20, 200)
        )
    log:
        "logs/test_gencode_corrections.log"
    wrapper:
        "master/bio/ensembl/remove_patch_cdna"
