name: rbt fix-iupac-alleles
url: https://github.com/rust-bio/rust-bio-tools
description: >
  Convert any IUPAC codes in alleles into Ns (in order to comply with VCF 4 specs).
authors:
  - Thibault Dayris
input:
  - Path to variants to fix (VCF, BCF or VCF.GZ)
output:
  - Path to variants with fixed alleles (VCF, BCF, or VCF.GZ)
notes: |
  No optional parameter is expected in this wrapper.
