from snakemake.utils import min_version

min_version("9.13.1")


module genome_statistics:
    config:
        {
            "pathvars": {
                "genome_sequence": "genome.fasta",
                "genome_annotation": "genome.gtf",
                "agat_config": "agat_config.yaml",
                "reference": "reference",
                "species": "saccharomyces_cerevisiae",
                "build": "R64-1-1",
                "release": "105",
                "benchmark": "benchmark",
                "tmp": "tmp",
                "log": "logs",
            }
        }
    meta_wrapper:
        "file:.."


use rule * from genome_statistics
