from snakemake.utils import min_version

min_version("9.13.1")


configfile: "config.yaml"


rule target:
    input:
        "resources/saccharomyces_cerevisiae.R64-1-1.105/statistics/statistics.yaml",


module genome_statistics:
    config:
        config
    meta_wrapper:
        "file:.."


use rule * from genome_statistics
