rule test_deeptools_plot_pca:
    input:
        "bins.npz",
    output:
        plot="pca.svg",
        matrix="pca.tab",  # Optional
    log:
        "pca.log",
    threads: 1
    params:
        extra="--ntop 0",
    wrapper:
        "master/bio/deeptools/plotpca"
