rule test_maftools_readmaf:
    input:
        maf = "variants.maf"
    output:
        rds = "results/maf.RDS",
        summary = "results/prefix_summary.txt"
    params:
        summary_prefix = "results/prefix"
    wrapper:
        "master/bio/maftools/readmaf"
