rule test_epic:
    input:
        quant="quantification.tsv"
    output:
        histogram="celltypes.hist.png",
        dotplot="celltypes.dotplot.png",
        tsv="celltypes.tsv",
        rds="celltypes.RDS"
    wrapper:
        "master/bio/immunedeconv/epic"
