rule test_bedtools_maskfasta:
    input:
        bed="intervals.bed",
        fasta="sequences.fasta"
    output:
        "masked.fasta"
    params:
        extra=""
    wrapper:
        "master/bio/bedtools/maskfasta"