rule test_bedtools_maskfasta:
    input:
        fasta="sequences.fa",
        bed="mask.bed"
    output:
        "masked.fasta"
    params:
        extra=""
    wrapper:
        "master/bio/bedtools/maskfasta"
