rule test_split_design:
    input:
        design="coldata.tsv"
    output:
        "test/DGE_considering_factor_Cond_comparing_test_A_vs_ref_B.tsv"
    log:
        "split_design.log"
    wrapper:
        "master/bio/BiGR/split_design"
