wildcard_constraints:
  species=r"saccharomyces_cerevisiae|homo_sapiens|mus_musculus",
  build=r"R64-1-1|GRCh38|GRCh37|GRCm38|GRCm39",
  release=r"116|75|102|115",
  gxf=r"gtf|gff|gff3",
  seqtype=r"dna|cdna|cds",


rule target:
    input:
        dna_sequence=expand(
            "resources/{species_build_release}/sequences/{species_build_release}.dna.{ext}",
            species_build_release=config["species_build_release"],
            ext={"chrom_sizes.tsv", "fasta.fai", "dict", "fasta", "2bit"},
        ),
        genome_annotation=expand(
            "resources/{species_build_release}/annotations/{species_build_release}.{gxf}",
            species_build_release=config["species_build_release"],
            gxf={"gtf", "gff3"},
        ),
        genome_statistics=expand(
            "resources/{species_build_release}/statistics/statistics.yaml",
            species_build_release=config["species_build_release"],
        ),


module download_genome_sequences:
    meta_wrapper:
        f"{config['git_repo']}/download_genome_annotation"
    config:
        {
            "homo_sapiens": config["homo_sapiens"],
            "saccharomyces_cerevisiae": config["saccharomyces_cerevisiae"],
            "mus_musculus": config["mus_musculus"],
        }

use rule * from download_genome_sequences


module download_genome_annotation:
    meta_wrapper:
        f"{config['git_repo']}/download_genome_sequences"
    config:
        {"genome_sequence": "<resources>/{species}.{build}.{release}/sequences/{species}.{build}.{release}.dna.fasta"}


use rule * from download_genome_annotation


module genome_statistics:
    meta_wrapper:
        f"{config['git_repo']}/genome_statistics"
    config:
        {
            "genome_sequence": "<resources>/{species}.{build}.{release}/sequences/{species}.{build}.{release}.dna.fasta",
            "genome_annotation": "<resources>/{species}.{build}.{release}/annotations/{species}.{build}.{release}.gtf",
            "agat_config": "<resources>/{species}.{build}.{release}/annotations/{species}.{build}.{release}.agat_gff3_config.yaml",
        }


use rule * from genome_statistics
