wildcard_constraints:
    species=r"saccharomyces_cerevisiae|homo_sapiens|mus_musculus",
    build=r"R64-1-1|GRCh38|GRCh37|GRCm38|GRCm39",
    release=r"116|75|102|115",
    gxf=r"gtf|gff|gff3",
    seqtype=r"dna|cdna|cds",


container: "docker://quay.io/condaforge/miniforge3@sha256:962cf538c4f7b624bac1452a95cc88fb2013a8188445b9b6af85ee748ca5d3c8"


config["genome_sequence"] = (
    "<resources>/{species}.{build}.{release}/sequences/{species}.{build}.{release}.dna.fasta"
)
config["genome_annotation"] = (
    "<resources>/{species}.{build}.{release}/annotations/{species}.{build}.{release}.gtf"
)
config["agat_config"] = (
    "<resources>/{species}.{build}.{release}/annotations/{species}.{build}.{release}.agat_gff3_config.yaml"
)


rule target:
    input:
        dna_sequence=expand(
            "resources/{species_build_release}/sequences/{species_build_release}.dna.{ext}",
            species_build_release=config["species_build_release"],
            ext={"chrom_sizes.tsv", "fasta.fai", "dict", "fasta", "2bit"},
        ),
        genome_annotation=expand(
            "resources/{species_build_release}/annotations/{species_build_release}.{gxf}",
            species_build_release=config["species_build_release"],
            gxf={"gtf", "gff3"},
        ),
        genome_statistics=expand(
            "resources/{species_build_release}/statistics/statistics.yaml",
            species_build_release=config["species_build_release"],
        ),


module download_genome_sequences:
    config:
        config
    meta_wrapper:
        f"{config['git_repo']}/download_genome_annotation"


use rule * from download_genome_sequences


module download_genome_annotation:
    config:
        config
    meta_wrapper:
        f"{config['git_repo']}/download_genome_sequences"


use rule * from download_genome_annotation


module genome_statistics:
    config:
        config
    meta_wrapper:
        f"{config['git_repo']}/genome_statistics"


use rule * from genome_statistics
