rule test_mixcr_assemble:
    input:
        "alignment.vdjca"
    output:
        vdjca="collected.vdjca",
        report="report.txt"
    params:
        extra=""
    wrapper:
        "master/bio/mixcr/assemblepartial"
