name: cluster profiler enrichplot
description: Plot Cluster Profiler results
url: https://yulab-smu.top/biomedical-knowledge-mining-book/universal-api.html
authors:
  - Thibault Dayris
input:
  - enrichment: A cluster profiler enricher or gsea result as RDS binary file.
output:
  - barplot: Enrichment analysis result as a PNG formatted image representing a barplot of selected/best enriched terms.
  - dotplot: Enrichment analysis result as a PNG formatted image representing a dotplot of selected/best enriched terms.
  - cnetplot: Linkage of gene and terms, as a PNG formatted image representing a concept network of enriched terms.
  - heatplot: Linkage of gene and terms, as a PNG formatted image representing a coloured heatmap.
  - emapplot: Linkage of terms, as PNG formatted image representing the network.
  - upsetplot: Linkage of gene and terms, as a PNG formatted image representing up-sets.
  - pmcplot: Pubmed central trend plot, as a PNG formatted image.
  - ridgeplot: Pre-ranked gene lists, as a PNG formatted image.
  - gseaplot: Running score and pre-ranked weights, as a PNG formatted image.
params:
  - png_extra: Optional parameters for `grDevices::png <https://www.rdocumentation.org/packages/grDevices/versions/3.4.1/topics/png>`_ .
  - barplot_extra: Optional parameters for `graphics::barplot <https://rdrr.io/r/graphics/barplot.html>`_ .
  - dotplot_extra: Optional parameters for `enrichplot::dotplot <https://rdrr.io/bioc/enrichplot/man/dotplot.html>`_ .
  - cnetplot_extra: Optional parameters for `enrichplot::cnetplot <https://rdrr.io/bioc/enrichplot/man/cnetplot.html>`_ .
  - heatplot_extra: Optional parameters for `enrichplot::heatplot <https://rdrr.io/bioc/enrichplot/man/heatplot.html>`_ .
  - emapplot_extra: Optional parameters for `enrichplot::emapplot <https://rdrr.io/bioc/enrichplot/man/emapplot.html>`_ .
  - upsetplot_extra: Optional parameters for `enrichplot::upsetplot <https://rdrr.io/bioc/enrichplot/man/upsetplot-methods.html>`_ .
  - pmcplot_extra: Optional parameters for `enrichplot::pmcplot <https://rdrr.io/bioc/enrichplot/man/pmcplot.html>`_ .
notes: |
  * ridgeplot,and gseaplot, are only available with GSEA analysis. Requesting these plots with enricher input will raise an error.