rule test_enrich_upsetplot:
    input:
        rds = "enriched.RDS"
    output:
        png = "upsetplot.png"
    params:
        upsetplot_extra = "n = 5"
    wrapper:
        "master/bio/clusterProfiler/upsetplot"
