rule test_salmon_decoy:
    input:
        transcriptome="transcriptome.fasta.gz",
        genome="genome.fasta.gz",
    output:
        gentrome="gentrome.fasta.gz",
        decoys="decoys.txt",
    log:
        "decoys.log",
    threads: 2
    wrapper:
        "master/bio/salmon/decoys"
