name: dysk
url: https://github.com/Canop/dysk
description: A linux utility to get information on filesystems, like df but better
authors:
  - Thibault Dayris
input:
  - Optional path to a mointing point to analyse
output:
  - Path to file system information (txt, json, csv or tsv)
params:
  - extra: Optional parameters besides `--csv` or `--json`.
notes: |
  In case of TSV format, the `--csv-separator` parameter is already handled
  automatically.
