rule test_enrichDO:
    input:
        rds = "geneList.RDS"
    output:
        rds = "enrichDO.RDS",
        tsv = "enrichDO.tsv"
    params:
        enrichDO_extra = "ont = 'DOLite'"
    wrapper:
        "master/bio/clusterProfiler/enrichDO"
