jobs: 7
local-cores: 7
keep-going: true
rerun-triggers: "mtime"
rerun-incomplete: true
shadow-prefix: "temp/shadow"
report: "report.zip"
report-after-run: true
printshellcmds: true
show-failed-logs: true
benchmark-extended: true
jobscript: "jobscript.sh"
software-deployment-method:
  - apptainer
  - conda
