rule muscle_fasta:
    input:
        fasta="{sample}.fa",  # Input fasta file
    output:
        alignment="{sample}.fas",  # Output alignment file
    log:
        "logs/muscle/{sample}.log",
    threads: 2
    params:
        extra="-refineiters 50",  # Additional arguments
    wrapper:
        "master/bio/muscle"


rule muscle_super5:
    input:
        fasta="{sample}.fa",
    output:
        alignment="{sample}.super5.fas",
    log:
        "logs/muscle/{sample}.super5.log",
    threads: 2
    params:
        super5=True,
        extra="-refineiters 50",
    wrapper:
        "master/bio/muscle"
