rule test_SomaticSignatures_motifMatrix:
    input:
        context = "context.rds"
    output:
        rds = "motifs.rds",
        tsv = "motifs.tsv"
    params:
        extra = "group = 'sampleNames'"
    wrapper:
        "master/bio/SomaticSignatures/motifMatrix"
