rule test_sexdeterrmine:
    input:
        depth="samples.depth.tsv",
    output:
        tsv="results.tsv",
        json="results.json",
    log:
        "sexdeterrmine.log",
    threads: 1
    wrapper:
        "master/bio/sexdeterrmine"
