rule shovill:
    input:
        r1="reads/{sample}_R1.fq.gz",
        r2="reads/{sample}_R2.fq.gz",
    output:
        raw_assembly="assembly/{sample}.{assembler}.assembly.fa",
        contigs="assembly/{sample}.{assembler}.contigs.fa",
    log:
        "logs/shovill/{sample}.{assembler}.log",
    threads: 1
    params:
        extra="",
    wrapper:
        "master/bio/shovill"
