rule test_cpat:
    input:
        hexamer_table = "hexamer_table",
        logit_model = "logit_model.logit.RData",
        transcripts = "transcripts.fasta"
    output:
        "cpat_results.tsv"
    wrapper:
        "master/bio/cpat/cpat"
