rule art_profiler_illumina:
    input:
        "data/{sample}.fq",
    output:
        "profiles/{sample}.txt",
    log:
        "logs/art_profiler_illumina/{sample}.log",
    threads: 2
    params:
        "",
    wrapper:
        "master/bio/art/profiler_illumina"
