rule test_rseqc_bam_stat:
    input:
        "a.bam",
    output:
        "a.stats",
    log:
        "bastat.log",
    threads: 1
    params:
        extra="--mapq 5",
    wrapper:
        "master/bio/rseqc/bam_stat"
