rule test_oncokb_annotate:
    input:
        vcf="in.vcf",
        oncokb="db.csv"
    output:
        vcf="out.vcf"
    log:
        "oncokb.log"
    wrapper:
        "master/bio/BiGR/oncokb_annotate"
