rule homer_mergePeaks:
    input:
        # input peak files
        "peaks/{sample1}.peaks",
        "peaks/{sample2}.peaks",
    output:
        "merged/{sample1}_{sample2}.peaks",
    log:
        "logs/mergePeaks/{sample1}_{sample2}.log",
    params:
        extra="-d given",  # optional params, see homer manual
    wrapper:
        "master/bio/homer/mergePeaks"
