rule test_deeptools_multibigwigsummary:
    input:
        bigwigs=[
            "C0535ACXX_LJA143_0_chr1.bw",
            "C0535ACXX_LJA156_0_chr1.bw",
        ],
        # Optional path to blacklist file
        # blacklist="",
        # Optional path to regions bed file
        # bed="",
    output:
        npz="multibigwig.npz",
        # Optional path to raw_counts
        raw_counts="multibigwig.counts",
    params:
        extra="",
    wrapper:
        "master/bio/deeptools/multibigwigsummary"
