from snakemake.utils import min_version

min_version("9.13.1")

config = {
    "pathvars": {
        "tmp": "tmp",
        "benchmark": "benchmark",
        "log": "log",
    },
    "irods_host": "~/.irods/irods_environment.json",
    "irods_prefix": ["/odin/kdi"],
    "cold_storage": [
        "/mnt/glusterv0",
        "/mnt/install",
    ],
    "samples_table": "resources/samples_table.csv",
    "samples": [
        "resequenced_sample", "plain_sample",
    ],
}


rule target:
    input:
        expand(
            "tmp/fastcat_fastq/{sample}.{stream}.fastq.gz",
            sample=config["samples"],
            stream={1, 2},
        ),
        "results/fastq_qc/fastcat_per_fastq_file_qc.csv.gz",


module access_fastq_files_pair:
    config:
        config
    meta_wrapper:
        "file:.."


use rule * from access_fastq_files_pair
