from snakemake.utils import min_version

min_version("9.13.1")

container: "docker://quay.io/condaforge/miniforge3:26.5.3-0"

configfile = "config.yaml"

rule target:
    input:
        expand(
            "tmp/fastcat_fastq/{sample}.{stream}.fastq.gz",
            sample=config["samples"],
            stream={1, 2},
        ),
        "results/fastq_qc/fastcat_per_fastq_file_qc.csv.gz",


module access_fastq_files_pair:
    config:
        config
    meta_wrapper:
        "file:.."


use rule * from access_fastq_files_pair
