from snakemake.utils import min_version

min_version("9.13.1")


configfile: "config.yaml"


module access_fastq_files_pair:
    config:
        config
    meta_wrapper:
        "file:.."


use rule * from access_fastq_files_pair
