wildcard_constraints:
  species=r"saccharomyces_cerevisiae|homo_sapiens|mus_musculus",
  build=r"R64-1-1|GRCh38|GRCh37|GRCm38|GRCm39",
  release=r"116|75|102|115",
  gxf=r"gtf|gff|gff3",
  seqtype=r"dna|cdna|cds",

rule target:
    input:
          
