rule purge_dups_ngscstat:
    input:
        bam="reads.bam",
    output:
        cov="out/ngscstat.cov",
        stat="out/ngscstat.stat",
    log:
        "logs/ngscstat.log",
    threads: 1
    params:
        extra="",
    wrapper:
        "master/bio/purge_dups/ngscstat"
