#!/usr/bin/bash
sed -i 's/root/m_deloger/g' arriba_calling_rule
sed -i 's/root/m_deloger/g' arriba_drawing_rule
sed -i 's/root/m_deloger/g' arriba_normalization_rule
sed -i 's/root/m_deloger/g' bcftools_concat_cancer_rule
sed -i 's/root/m_deloger/g' bcftools_concat_wes_rule
sed -i 's/root/m_deloger/g' bcftools_concat_wgs_rule
sed -i 's/root/m_deloger/g' bcftools_merge_wts_wes_rule
sed -i 's/root/m_deloger/g' bcftools_reheader_cancer_rule
sed -i 's/root/m_deloger/g' bedtools_wes_rule
sed -i 's/root/m_deloger/g' bwa_mem_cancer_rule
sed -i 's/root/m_deloger/g' bwa_mem_cancer_rule.bak
sed -i 's/root/m_deloger/g' fastq_concat_rule
sed -i 's/root/m_deloger/g' fastq_concat_rule
sed -i 's/root/m_deloger/g' fusion_catcher_rule
sed -i 's/root/m_deloger/g' fusion_normalisation_script_rule
sed -i 's/root/m_deloger/g' gatk_applybqsr_wgs_cancer_rule
sed -i 's/root/m_deloger/g' gatk_applybqsr_wgs_rule
sed -i 's/root/m_deloger/g' gatk_applybqsr_wts_rule
sed -i 's/root/m_deloger/g' gatk_base_recalibrator_wgs_cancer_rule
sed -i 's/root/m_deloger/g' gatk_base_recalibrator_wgs_rule
sed -i 's/root/m_deloger/g' gatk_base_recalibrator_wts_rule
sed -i 's/root/m_deloger/g' gatk_filter_mutect_calls_wes_rule
sed -i 's/root/m_deloger/g' gatk_filter_mutect_calls_wes_tumor_only_rule
sed -i 's/root/m_deloger/g' gatk_haplotype_caller_wgs_cancer_rule
sed -i 's/root/m_deloger/g' gatk_haplotype_caller_wts_rule
sed -i 's/root/m_deloger/g' gatk_mergevcf_mutect2_rule
sed -i 's/root/m_deloger/g' gatk_mutect2_wes_rule
sed -i 's/root/m_deloger/g' gatk_mutect2_wes_tumor_only_rule
sed -i 's/root/m_deloger/g' gatk_select_variants_mutect_wes_rule
sed -i 's/root/m_deloger/g' msisensor_rule
sed -i 's/root/m_deloger/g' picard_collect_insert_size_metrics_wes_rule
sed -i 's/root/m_deloger/g' picard_collect_insert_size_metrics_wgs_cancer_rule
sed -i 's/root/m_deloger/g' picard_collect_insert_size_metrics_wts_rule
sed -i 's/root/m_deloger/g' picard_markdup_wgs_rule
sed -i 's/root/m_deloger/g' picard_markdup_wts_rule
sed -i 's/root/m_deloger/g' quality_wes_changement_rule
sed -i 's/root/m_deloger/g' rsync_vcf_tmb_rule
sed -i 's/root/m_deloger/g' sambamba_flagstat_wgs_rule
sed -i 's/root/m_deloger/g' sambamba_flagstat_wts_rule
sed -i 's/root/m_deloger/g' sambamba_index_bam_rule
sed -i 's/root/m_deloger/g' sambamba_index_genome_rule
sed -i 's/root/m_deloger/g' sambamba_index_wgs_markdup_rule
sed -i 's/root/m_deloger/g' sambamba_index_wgs_rule
sed -i 's/root/m_deloger/g' sambamba_index_wts_markdup_rule
sed -i 's/root/m_deloger/g' sambamba_index_wts_rule
sed -i 's/root/m_deloger/g' sambamba_merge_facet_rule
sed -i 's/root/m_deloger/g' sambamba_merge_wgs_rule
sed -i 's/root/m_deloger/g' sambamba_merge_wts_rule
sed -i 's/root/m_deloger/g' sambamba_slice_wgs_rule
sed -i 's/root/m_deloger/g' sambamba_slice_wts_rule
sed -i 's/root/m_deloger/g' signature_mut_matrix_decomp_rule
sed -i 's/root/m_deloger/g' signature_mut_matrix_ext_rule
sed -i 's/root/m_deloger/g' signature_mut_matrix_gen_rule
sed -i 's/root/m_deloger/g' snpeff_tmb_rule
sed -i 's/root/m_deloger/g' snpeff_wts_wes_rule
sed -i 's/root/m_deloger/g' snpsift_annotate_leaves_trio_wgs_rule
sed -i 's/root/m_deloger/g' snpsift_annotate_TMB_rule
sed -i 's/root/m_deloger/g' snpsift_annotate_wes_rule
sed -i 's/root/m_deloger/g' snpsift_dbnsfp_trio_GRCh38_wgs_rule
sed -i 's/root/m_deloger/g' snpsift_dbnsfp_trio_wgs_rule
sed -i 's/root/m_deloger/g' snpsift_phastcons_trio_wgs_rule
sed -i 's/root/m_deloger/g' star_arriba_rule
sed -i 's/root/m_deloger/g' star_cancer_rule
sed -i 's/root/m_deloger/g' star_fusion_inspector_rule
sed -i 's/root/m_deloger/g' star_fusion_rule
sed -i 's/root/m_deloger/g' tabix_cancer_vcf_wes_rule
sed -i 's/root/m_deloger/g' tabix_cancer_vcf_wgs_rule
sed -i 's/root/m_deloger/g' tabix_cancer_vcf_wts_rule
sed -i 's/root/m_deloger/g' tabix_wes_rule
sed -i 's/root/m_deloger/g' tmb_curie_rule
sed -i 's/root/m_deloger/g' vt_decompose_cancer_database_rule
sed -i 's/root/m_deloger/g' vt_decompose_cancer_tmb_rule
sed -i 's/root/m_deloger/g' vt_decompose_cancer_wes_rule
sed -i 's/root/m_deloger/g' vt_decompose_cancer_wgs_rule
sed -i 's/root/m_deloger/g' vt_decompose_cancer_wts_rule
sed -i 's/root/m_deloger/g' vt_normalize_uniq_cancer_database_rule
sed -i 's/root/m_deloger/g' vt_normalize_uniq_cancer_tmb_rule
sed -i 's/root/m_deloger/g' vt_normalize_uniq_cancer_wes_rule
sed -i 's/root/m_deloger/g' vt_normalize_uniq_cancer_wgs_rule
sed -i 's/root/m_deloger/g' vt_normalize_uniq_cancer_wts_rule

