rule sambamba_markdup:
    input:
        "mapped/{sample}.bam",
    output:
        "mapped/{sample}.rmdup.bam",
    log:
        "logs/sambamba-markdup/{sample}.log",
    threads: 8
    params:
        extra="-r",  # optional parameters
    wrapper:
        "master/bio/sambamba/markdup"
