rule epic:
    input:
        treatment="bed/test.bed",
        background="bed/control.bed",
    output:
        enriched_regions="epic/enriched_regions.csv",  # required
        bed="epic/enriched_regions.bed",  # optional
        matrix="epic/matrix.gz",  # optional
    log:
        "logs/epic/epic.log",
    threads: 1  # optional, defaults to 1
    params:
        genome="hg19",  # optional, default hg19
        extra="-g 3 -w 200",  # "--bigwig epic/bigwigs"
    wrapper:
        "master/bio/epic/peaks"
