rule bcftools_sort:
    input:
        "{sample}.bcf",
    output:
        "{sample}.sorted.bcf",
    log:
        "logs/bcftools/sort/{sample}.log",
    resources:
        mem_mb=8000,
    params:
        # Set to True, in case you want uncompressed BCF output
        uncompressed_bcf=False,
        # Extra arguments
        extras="",
    wrapper:
        "master/bio/bcftools/sort"
