rule test_msisensor_scan:
    input:
        "genome.fasta",
    output:
        "microsat.list",
    log:
        "logs/msisensor_scan.log",
    threads: 1
    params:
        extra="",
    message:
        "Testing MSISensor scan"
    wrapper:
        "master/bio/msisensor/scan"
