rule homer_getDifferentialPeaks:
    input:
        # peak/bed file to be tested
        peaks="{sample}.peaks.bed",
        # tagDirectory of first sample
        first="tagDir/{sample}",
        # tagDirectory of sample to compare
        second="tagDir/second",
    output:
        "{sample}_diffPeaks.txt",
    log:
        "logs/diffPeaks/{sample}.log",
    params:
        extra="",  # optional params, see homer manual
    wrapper:
        "master/bio/homer/getDifferentialPeaks"
