rule test_mixcr_assemble:
    input:
        "alignment.vdjca"
    output:
        clns="assembly.clns",
        report="report.txt"
    params:
        extra=""
    wrapper:
        "master/bio/mixcr/assembleContigs"
