rule test_pcaexplorer_pcacorrs:
    input:
        dst = "vst.RDS",
        dds = "dds.RDS"
    output:
        png = "plot.png"
    message:
        "Testing pcaExplorer PCA Correlations"
    threads:
        1
    resources:
        mem_mb = (
            lambda wildcards, attempt: min(attempt * 1024, 10240)
        ),
        time_min = (
            lambda wildcards, attempt: min(attempt * 20, 200)
        )
    log:
        "logs/test_pcaexplorer_pcacorrs.log"
    wrapper:
        "master/bio/pcaExplorer/plotCorrs"
