rule vembrane_table:
    input:
        vcf="in.vcf",
    output:
        vcf="table/out.tsv",
    log:
        "logs/vembrane.log",
    params:
        expression="CHROM, POS, ALT, REF",
        extra="",
    wrapper:
        "master/bio/vembrane/table"
