rule GroupReads:
    input:
        "mapped/a.bam",
    output:
        bam="mapped/{sample}.gu.bam",
        hist="mapped/{sample}.gu.histo.tsv",
    log:
        "logs/fgbio/group_reads/{sample}.log",
    params:
        extra="-s adjacency --edits 1",
    wrapper:
        "master/bio/fgbio/groupreadsbyumi"
