rule cutadapt:
    input:
        "reads/{sample}.fastq",
    output:
        fastq="trimmed/{sample}.fastq",
        qc="trimmed/{sample}.qc.txt",
    log:
        "logs/cutadapt/{sample}.log",
    threads: 4  # set desired number of threads here
    params:
        adapters="-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC",
        extra="-q 20",
    wrapper:
        "master/bio/cutadapt/se"
