name: snpeff2vep
description: |
  Writes a new "VEP_ANN" tag in INFO field of each variant in a given snpeff-annotated VCF.
  This VEP_ANN field has the expected information produced by snpeff, in the expected
  format from VEP. This is used as a compatibility tool for downstream reporting tools.
author:
  - Thibault Dayris
input:
  - vcf: Path to the input vcf file
output:
  - vcf: Path to the annotated vcf file