rule test_simpleaf_set_path:
    # input:
        # salmon="",  # Optional path to salmon
        # piscem="",  # Optional path to piscem
        # alevin_fry="",  # Optional path to alevin_fry
        # pyroe="",  # Optional path to pyroe
    output:
        cache="simpleaf_info.json"
    threads: 1
    log:
        "logs/simpleaf.log"
    params:
        extra="",
    wrapper:
        "master/bio/simpleaf/setpaths"