from snakemake.utils import min_version

min_version("9.13.1")


configfile: "config.yaml"


module bowtie2_sambamba:
    config:
        config
    meta_wrapper:
        "file:.."


use rule * from bowtie2_sambamba
