rule test_pharmkdb_annotate:
    input:
        vcf="in.vcf",
        clinical_ann_metadata="pharmk.db"
    output:
        vcf="out.vcf"
    log:
        "pharmkdb.log"
    wrapper:
        "master/bio/BiGR/pharmkdb_annotate"
