rule csv_report:
    input:
        # a csv formatted file containing the data for the report
        "report.csv",
    output:
        # path to the resulting report directory
        directory("qc_data"),
    log:
        "logs/rbt-csv-report",
    params:
        extra="--sort-column 'contig length'",
    wrapper:
        "master/bio/rbt/csvreport"
