rule test_consensus_cluster_plus:
    input:
        expr_mat="table.tsv"
    output:
        res_dir=directory("ccp")
    log:
        "logs/consensusclusterplus.log"
    wrapper:
        "master/bio/consensusclusterplus"
