rule meryl_count:
    input:
        fasta="{genome}.fasta",
    output:
        directory("{genome}/"),
    log:
        "logs/meryl_count/{genome}.log",
    threads: 2
    resources:
        mem_mb=2048,
    params:
        command="count",
        extra="k=32",
    wrapper:
        "master/bio/meryl/count"
