rule test_eacon_annotate:
    input:
        rds = "{sample}/ASCAT/L2R/{sample}.SEG.ASCAT.RDS",
        grd = "grd.pl",
        database = "database"
    output:
        multiext(
            "{sample}/ASCAT/L2R/{sample}",
            ".BAF.png",
            ".Cut.acbs",
            ".Instab.txt",
            ".INT.png",
            ".L2R.G.png",
            ".L2R.K.png",
            ".TargetGenes.txt",
            ".TruncatedGenes.txt"
        ),
        expand(
            "{sample}/ASCAT/L2R/chromosomes/{chromosome}",
            chromosome = [f"chr{i}.png" for i in list(map(str, range(1, 23))) + ["X", "Y"]],
            allow_missing=True
        ),
        "{sample}/ASCAT/L2R/{sample}.REPORT.html",
        directory("{sample}/ASCAT/L2R/{sample}_solo.hg19")
    wrapper:
        "master/bio/eacon/annotate"
