rule test_eacon_annotate:
    input:
        rds = "{sample}/ASCAT/L2R/{sample}.SEG.ASCAT.RDS",
        grd = "grd.pl",
        database = "database"
    output:
        multiext(
            "{sample}/ASCAT/L2R/{sample}",
            ".BAF.png",
            ".Cut.acbs",
            ".Instab.txt",
            ".INT.png",
            ".L2R.G.png",
            ".L2R.K.png",
            ".TargetGenes.txt",
            ".TruncatedGenes.txt"
        )
    wrapper:
        "master/bio/eacon/annotate"
