rule test_eacon_annotate:
    input:
        rds = "file.RDS",
        grd = "grd.pl",
        database = "database/"
    output:
        "report.html"
    wrapper:
        "master/bio/eacon/annotate"
