rule samtools_fixmate:
    input:
        "mapped/{input}",
    output:
        "fixed/{input}",
    log:
        "{input}.log",
    threads: 1
    params:
        extra="",
    message:
        "Fixing mate information in {wildcards.input}"
    wrapper:
        "master/bio/samtools/fixmate/"
