rule test_analyze_cpat:
    input:
        switch_list = "switch_list.RDS",
        cpat = "cpat_results.txt"
    output:
        rds = "switch_list_with_cpat.RDS"
    wrapper:
        "master/bio/isoformSwitchAnalyzeR/analyzeCPAT"
