rule test_chipseeker_covplot:
    input:
        rds = "bampe.narrowPeak.RDS"
    output:
        png = "covplot.png"
    params:
        extra = "weightCol='V5'"
    wrapper:
        "master/bio/chipseeker/covplot"
