name: dorado mapping
url: https://github.com/nanoporetech/ont_fast5_api
description: >
  This meta-wrapper downloads and prepare dorado resources and align pod5 reads
  to given genome.

  This meta-wrapper includes the following steps:

    +---------------+---------------+-------------------------------------+
    | Step          | Tool          | Reason                              |
    +===============+===============+=====================================+
    | Download      | dorado        | Get dorado model                    |
    +---------------+---------------+-------------------------------------+
    | Basecalling   | dorado        | Get reads as ubam                   |
    +---------------+---------------+-------------------------------------+
    | Index         | minimap2      | Index fasta genome                  |
    +---------------+---------------+-------------------------------------+
    | Mapping       | dorado        | Align read on genome                |
    +---------------+---------------+-------------------------------------+
authors:
  - Thibault Dayris
pathvars:
  default:
    - results
    - logs
    - temp
    - resources
    - benchmarks
