rule homer_findPeaks:
    input:
        # tagDirectory of sample
        tag="tagDir/{sample}",
        # tagDirectory of control background sample - optional
        control="tagDir/control",
    output:
        "{sample}_peaks.txt",
    log:
        "logs/findPeaks/{sample}.log",
    params:
        # one of 7 basic modes of operation, see homer manual
        style="histone",
        extra="",  # optional params, see homer manual
    wrapper:
        "master/bio/homer/findPeaks"
