rule ConsensusReads:
    input:
        "mapped/a.bam",
    output:
        "mapped/{sample}.m3.bam",
    log:
        "logs/fgbio/consensus_reads/{sample}.log",
    params:
        extra="-M 3",
    wrapper:
        "master/bio/fgbio/callmolecularconsensusreads"
