rule samtools_calmd:
    input:
        aln="{sample}.bam",  # Can be 'sam', 'bam', or 'cram'
        ref="genome.fasta",
    output:
        "{sample}.calmd.bam",
    log:
        "{sample}.calmd.log",
    threads: 2
    params:
        extra="-E",  # optional params string
    wrapper:
        "master/bio/samtools/calmd"
