rule download:
    output:
        # Overture maps datafile
        path="results/division_boundary.parquet",
    log:
        "logs/overturemaps/download.log",
    threads: 1
    params:
        # file format to request
        format="geoparquet",
        # Data type to request
        type="division_boundary",
        # bounding box in "west,south,east,north" format
        bbox=[15.87, -19.02, 28.88, -9.66],  # optional
    wrapper:
        "master/geo/overturemaps/download"
